ministryofjustice/cla_backend

- cla_backend/apps/call_centre/views.py
- cla_backend/apps/checker/views.py
- cla_backend/apps/cla_eventlog/tests/test_registry.py
- cla_backend/apps/legalaid/tests/views/mixins/eligibility_check_api.py
- cla_backend/apps/legalaid/views.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MIDigitalCaseTypes.sql
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
* Create a report to show different states a digital case can be in
* Log on the elgibility check the state it was at every time it is saved
> Log the eligibility state when a case is created

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/checker/tests/api/test_case_api.py
- cla_backend/apps/legalaid/forms.py
- cla_backend/apps/legalaid/tests/test_helpers.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MICB1sSLA.sql
This allows us to report on sms and voicemail cases breaking their 8hour sla.
> In addition to the sla_120 and sla_15 fields, add a sla_480 field on CBs

- cla_backend/apps/cla_eventlog/migrations/0008_edit_autovacuum_scale_factor_to_enable_statistics_to_update_more_freq.py
- cla_backend/apps/reports/sql/MIExtractByOutcome.sql
also add migration to enable more fine grained autoanalyize on
the cla_eventlog_log table as default wasn't good enough.
> update MI Extract By Outcome query to be quicker

- cla_backend/apps/core/fixtures/initial_groups.json
- cla_backend/apps/legalaid/migrations/0002_auto_20150417_1122.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/tasks.py
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/utils.py
- cla_backend/apps/reports/views.py
- cla_backend/templates/admin/reports/success_info.html
people do will feed it into a management information system.
the email address it uses is in the config repo
> add UI for triggering a background job that emails the anonomized db dump to

- cla_backend/apps/diagnosis/data/graph-2014.07.21.graphml
addition to graphml file due to change in law relating to homelessness in Wales.
Must go *live* on 27th April.
> edit to graphml file for 27th April

- cla_backend/settings/jenkins.py
Tested and working config for jenkins builds
> Change Jenkins settings.py to use env vars

- cla_backend/apps/diagnosis/data/checker-graph-2015.05.18.graphml
> graph ML copy tweak for accommodation

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/views.py
- cla_backend/apps/legalaid/views.py
Required for [cla_frontend#553](https://github.com/ministryofjustice/cla_frontend/pull/553)
[PT](https://www.pivotaltracker.com/story/show/91393910)
> CHS: Call Centre case filtering

- cla_backend/apps/call_centre/templates/call_centre/email/case_cb1_created.txt
now considers third party callbacks.
> minor fix for email alert sent when a callback is requested

- cla_backend/apps/diagnosis/data/checker-graph.graphml
- cla_backend/apps/diagnosis/data/checker-graph.graphml.tpl
- cla_backend/settings/base.py
[PT](https://www.pivotaltracker.com/story/show/97894490)
> Update Scope graph

- cla_backend/apps/call_centre/events.py
- cla_backend/apps/call_centre/forms.py
- cla_backend/apps/legalaid/events.py
- cla_backend/apps/legalaid/migrations/0004_auto_20150803_1443.py
- cla_backend/apps/legalaid/tests/test_events.py
- cla_backend/apps/legalaid/views.py
- cla_backend/apps/notifications/migrations/0001_initial.py
[PT#97809110](https://www.pivotaltracker.com/story/show/97809110)
> Additional outcome codes

- cla_backend/apps/legalaid/migrations/0006_case_old_eod_details.py
- cla_backend/apps/legalaid/migrations/0007_auto_20150818_1509.py
an abandoned EOD model caused an exception. not clear how EODs can be abandoned though
> complaints feature DB migration fix

- cla_backend/apps/diagnosis/data/checker-graph.graphml
- cla_backend/apps/diagnosis/data/checker-graph.graphml.tpl
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
most outcomes are F2F now
[Fixes #102843926]
> new immigration scope tree

- cla_backend/apps/reports/forms.py
if form field was not supplied, a KeyError was generated
> OBIEE export fix

- cla_backend/apps/reports/forms.py
if form field was not supplied, a KeyError was generated
> report form fix

- cla_backend/apps/complaints/events.py
- cla_backend/apps/complaints/tests/test_complaints_api.py
"Complaint transferred to specialist" option added to complaints.
> Add "Complaint transferred to specialist" option

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MISurveyExtract.sql
- related case refs for person related to case
- related cases for third party persons
> add case ref columns to personal details

- cla_backend/apps/timer/migrations/0003_auto_20170410_1527.py
- cla_backend/apps/timer/models.py
- cla_backend/apps/timer/tests/test_models.py
- cla_backend/apps/timer/tests/test_views.py
- Server time and DB time doesen't match so need to use db time for created and stopped for consistency
> Set timeer stopped time to current database time

- cla_backend/apps/diagnosis/data/checker-graph.graphml
- cla_backend/apps/diagnosis/data/checker-graph.graphml.tpl
- cla_backend/apps/diagnosis/data/graph.graphml
- cla_backend/apps/diagnosis/data/graph.graphml.tpl
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
Unfortunately the welsh copy was not translated and therefore it will be in English, There will be
another piece of work in the future that will update all translations from English to Welsh.
> Updates copy because of change to legislation.

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/utils.py
This is due to the fact that the system into which they are uploaded
assumes local (London) time and ignores timezone information. Timezone
information is still included in the dates, so that they are not ambiguous
and a system which does not ignore timezone information will be able
to read them correctly.
This uses the psql command SET LOCAL TIME ZONE, which will set the
time zone of the connection for the duration of the transaction.
This is to attempt to limit any possible side-effects, although as
all the reports are run off the replica and nothing else appears to
be, this shouldn't matter.
This is basically doing exactly the same as #454 but I was going to have
to rebase that anyway so I rewrote it a bit as well just for fun.
> Display timestamps in local time (GMT/BST) in CSV exports

- Dockerfile
E: Unable to fetch some archives, maybe run apt-get update or try with
--fix-missing?
> fixes an issue when trying to install from archives

- README.md
Documents the release process for this application for both non-production and production releases.
🔎 Nicer link to the new section: https://github.com/ministryofjustice/cla_backend/blob/release-process/README.md#releasing
None
> Release process

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
- cla_backend/apps/legalaid/tests/test_helpers.py
- cla_backend/apps/legalaid/utils/sla.py
This pull request pushes Docker images to Cloud Platform's ECR repo instead.
There is a test change in `cla_backend/apps/legalaid/tests/test_helpers.py:SLATimeHelperTestCase` due to a test failure around daylight savings. The original test failure is in https://circleci.com/gh/ministryofjustice/cla_backend/126.
Please see inline code comments for reasoning. There are two major changes in the test:
- test names reflect the expected outcome (instead of "works")
- day and time mutations were made explicit by the `self._change` function
> Use Cloud Platform's docker registry

- README.md
- cla_backend/apps/legalaid/views.py
Update Postgres version in README to match the in use version according to CircleCI config.
Note the postgres role troubleshooting step when it would be useful
> Note postgres role requirement and troubleshooting step earlier

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
Allow Provider I want to be able to record a new outcome code HAA for housing cases.
This is part of the 2018 contract changes.
> LGA-242 - New housing outcome code HAA

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
[LGA-33: New outcome code for family](url)
This pull request creates a new outcome code for family code FAA and places it inside the 2018 category spec, so that means that it will only be updated when the 2018 contract is put in motion. It also creates a tests that ensures that when this new code is included in a CSV file, and uploaded into the Case Handling System, it is able to be validated by the ProviderCSVValidator class.
> Outcome code for family

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
[LGA-240: New outcome code for Family XX 3](https://dsdmoj.atlassian.net/browse/LGA-240)
This pull request creates a new outcome code for family code FAB and places it inside the 2018 category spec, so that means that it will only be updated when the 2018 contract is put in motion. It also creates a tests that ensures that when this new code is included in a CSV file, and uploaded into the Case Handling System, it is able to be validated by the ProviderCSVValidator class.
> Outcome code for family 3

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
New outcome code for Housing HAB
> LGA-242 - New outcome code for Housing HAB

- README.md
Document the remaining steps to compile, push, and pull translations from Transifex.
Source and translations successfully pushed to and pulled from https://www.transifex.com/ministry-of-justice/cla-backend/
> LGA-491 & LGA-494 Document tested translation procedure

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
[New fixed fee code - Determination Fee - DF](https://dsdmoj.atlassian.net/browse/LGA-251)
This pull requests adds a test to make sure the fixed fee code DF is present. 
> Create test for fixed fee code df

- cla_backend/apps/diagnosis/data/graph.graphml
- cla_backend/apps/diagnosis/data/graph.graphml.tpl
- cla_backend/apps/legalaid/fixtures/initial_category.json
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
[CLA CHS 2018 Contract terminology change - Actions against the Police](https://dsdmoj.atlassian.net/browse/LGA-152l)
This ticket updates the category of law description of 'Actions against the Police' to 'Claims Against Public Authorities'. 
> LGA-152 Terminology change

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Amend error message for incorrect fixed fee code use as reported during UAT
> LGA-615 - Amend error message for incorrect fixed fee code use - non-2018 cases

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Apply 2013 validation rules for eligibility codes for 2018 Education and Discrimination cases
> LGA-610 - Apply 2013 validation rules for eligibility codes for 2018 Education and Discrimination cases

- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/tests/api/test_case_organisation_assignment.py
- cla_backend/apps/call_centre/urls.py
- cla_backend/apps/call_centre/utils/organisation/__init__.py
- cla_backend/apps/call_centre/views.py
- cla_backend/apps/legalaid/events.py
- cla_backend/apps/legalaid/views.py
Assigning cases that don't have organisation to current operators organisation
Related to https://github.com/ministryofjustice/cla_frontend/pull/664
> LGA-771 - Assigning cases organisation

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
Adding new referral and signposting LREP code
> LGA-907 - Adding new referral and signposting LREP code

- cla_backend/apps/diagnosis/graph.py
Adds a 'key' key to the nodes in the graph, and avoids translating it, so that it can be used programatically in the public site.
> LGA-885 - Add untranslated 'key' to nodes in graph

- cla_backend/apps/reports/tasks.py
Log exception raised during OBIEE extract
At the moment when an exception is raised during the obiee extract, it is caught and the `An error occurred creating the zip file` message is captured and shown to the user https://github.com/ministryofjustice/cla_backend/blob/master/cla_backend/apps/reports/tasks.py#L127. However even-though the exception is re-raised it's not being logged to sentry. This PR explicitly logs exception so that we can troubleshoot why the extract is failing
> WIP - LGA-1046 - Log exception raised during OBIEE extract

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
- bin/staging_deploy.sh
- cla_backend/settings/base.py
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values.yaml
Provides a deploy pipeline for Kubernetes (as far as staging) using Circle CI
> LGA-1073 Circle CI

- cla_backend/apps/knowledgebase/management/commands/general_and_government_addition.py
Add General and Government article categories
> LGA-1055 - Add General and Government article categories

- cla_backend/apps/reports/sql/MICB1sSLA.sql
- cla_backend/apps/reports/tests/test_mi_sla_report.py
Use case creation time for voicemail and SMS cases when checking if SLA 1/2 were met
> LGA 1051 - CB1 report: Use case creation time for voicemail and SMS cases

- bin/delete_uat_release.sh
> [TEST PR] Feature/multi branch deploy  merge test

- helm_deploy/cla-backend/values-dev.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
Add replica database config
Make replica database config optional on UAT and dev
> LGA-1215 - Add replica database config

- helm_deploy/cla-backend/templates/_helpers.tpl
- helm_deploy/cla-backend/templates/ingress.yaml
- helm_deploy/cla-backend/values.yaml
> LGA-1002 Configure IP whitelisting

- helm_deploy/cla-backend/templates/cron.yaml
- helm_deploy/cla-backend/values.yaml
Add HGS Wales Office IP address to the whitelist
> LGA01430 - Add HGS Wales Office IP address to the whitelist

- helm_deploy/cla-backend/values.yaml
Required.
In the case that a pod is recreated/recycled this will allow us to have more than 1 pod available
> Increase replica count to 3

- helm_deploy/cla-backend/templates/_helpers.tpl
- helm_deploy/cla-backend/values-staging.yaml
Add staging frontend to staging ingress
> LGA-1473 - Add staging frontend to staging ingress

- .circleci/config.yml
- .circleci/define_build_environment_variables
- bin/training_deploy.sh
- helm_deploy/cla-backend/values-training.yaml
Add deployment to training namespace
Approving production deployment deploys automatically to training as well
> LGA-1438 - Training environment setup

- .circleci/config.yml
Allow master to be deployed to uat environment
> LGA-1477  - Make master deployable on to cloud platform environments

- cla_backend/apps/call_centre/signals.py
- cla_backend/apps/cla_auth/forms.py
- cla_backend/apps/cla_auth/views.py
- cla_backend/apps/cla_eventlog/models.py
- cla_backend/apps/cla_provider/authentication.py
- cla_backend/apps/cla_provider/signals.py
- cla_backend/apps/cla_provider/views.py
- cla_backend/apps/core/admin/modeladmin.py
- cla_backend/apps/core/middleware.py
- cla_backend/apps/core/signals.py
- cla_backend/apps/legalaid/views.py
- cla_backend/apps/timer/models.py
- cla_backend/apps/timer/views.py
- cla_backend/settings/base.py
- requirements/base.txt
- Remove all instances of `statsd` from codebase
- Removed `django-statsd-mozilla` from the `requirements/base.txt` file
> LGA-1221 Statsd Removal

- requirements/base.txt
Use cla_common version with boxing day hours
> WIP - LGA-1567 - Use cla_common version with boxing day hours

- cla_backend/apps/diagnosis/data/checker-graph.graphml
- cla_backend/apps/diagnosis/data/checker-graph.graphml.tpl
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
- Changes family mediation question text
- Updated translation files
- Adds Welsh translation for new text
- Removes old text and translation
> LGA-1106 New text for Family Mediation question

- cla_backend/apps/diagnosis/graph.py
GraphImporter.process_nodes Fix Flake8 C901
> LGA-453  - GraphImporter.process_nodes Fix Flake8 C901

- helm_deploy/cla-backend/values.yaml
Hopefully will help with CHS timeouts and gateway errors.
This has already been applied in production. It is too early to tell if it's really helped, but it needs committing to keep it in place so that we can monitor it.
> LGA-1599 - Scale prod up to 5 pods

- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/test_tasks.py
- cla_backend/apps/legalaid/tests/mommy_recipes.py
This build on the previous release of this.  this time it deletes the M2M relationship between Personal details and contact research methods so that Personal Details can be deleted.
> LGA-1121 Old complaints showing 

- cla_backend/apps/knowledgebase/admin.py
- cla_backend/apps/knowledgebase/forms.py
- cla_backend/apps/knowledgebase/tests/admin/test_views.py
- cla_backend/apps/knowledgebase/tests/mommy_recipes.py
- cla_backend/apps/knowledgebase/tests/test_csv_user_import.py
- cla_backend/apps/knowledgebase/utils/csv_user_import.py
- cla_backend/apps/knowledgebase/utils/csv_user_import_mappings.py
- cla_backend/templates/admin/knowledgebase/csv-upload.html
- cla_backend/templates/admin/knowledgebase/custom_change_list.html
Add knowledgebase.models.Article import from CSV
There is already existing functionality to export knowledge base articles as a CSV. This PR introduces a way to re-import that CSV after it has been updated. So the process becomes:
- The user downloads the knowledge base articles export (/admin/reports/all-knowledgebase-articles/)
- Make their changes to the CSV
- Upload the CSV back (/admin/knowledgebase/article/import-csv/)
The first column of every row is the ID(pk) of the Article to make the changes to.
If the row to be imported is a new Article then the ID column must have a value of `NEW`
The KnowledgebaseCSVImporter.save uses a database transaction to make sure all the articles are written to database and if there is an error it should not commit the transaction.
> LGA-1558 - Knowledgebase articles bulk CSV import

- helm_deploy/cla-backend/templates/_helpers.tpl
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
amended env var to be configmap and added that to the helpers so we can change the env var more easily for reports.
> LGA 1707 Switching on new report

- helm_deploy/cla-backend/values-dev.yaml
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
Move frontend hostname and express server port into config
These were stored as secrets before but these values are not secretive values
> LGA-1713 - Move frontend hostname and express server port into config

- cla_backend/apps/cla_provider/fixtures/test_provider.json
Removed email addresses from fixture json file used in create_db
> LGA 1739 remove email addresses from db scripts

- helm_deploy/cla-backend/values.yaml
Use socket server service for production
> LGA-1713 - Use socket server service for production

- helm_deploy/cla-backend/values.yaml
Reverts ministryofjustice/cla_backend#725
> Revert "LGA-1713 - Use socket server service for production"

- helm_deploy/cla-backend/values.yaml
Reverts ministryofjustice/cla_backend#727
> Revert "Revert "LGA-1713 - Use socket server service for production""

- cla_backend/apps/reports/views.py
Return response in report audit and knowledgebase views
> Return response in report audit and knowledgebase views

- .circleci/config.yml
- amended circleci config to deploy uat to new live cluster
- amended circleci config to deploy static uat to new live cluster
> LGA 1917 deploy UAT to new cluster

- .circleci/config.yml
Deploy to staging on live cluster
> LGA-1917 deploy staging to live

- .circleci/config.yml
added deployment from training to new cluster
> LGA 1917 Deploy training to new cluster

- cla_backend/apps/guidance/fixtures/initial_guidance_notes.json
- cla_backend/apps/guidance/tests/test_full_text_search.py
added guidance to initial guidance notes
> LGA 1805 Guidance notes for disregards.

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
- cla_backend/apps/status/views.py
- Ensures that pushed docker image references are lower-case only (as required by docker)
- Uses a dev version (for now) of the e2e test suite CircleCI orb [defined in a cla-end-to-end-tests-PR](https://github.com/ministryofjustice/cla-end-to-end-tests/pull/10)
- Runs some commands as `pre-steps` to the orb's job, to override the cla_backend image used in the test
One or two tests are failing. I'm not certain how big an issue this is.
> LGA-1779 - e2e tests from orb

- .github/workflowssemgrep.yml
Adds a github action to run a semgrep scan on the repo when a pull request is created
> LGA-1969 - Add semgrep github action

- .circleci/config.yml
Deploy production to new live cluster
> LGA-1920 - Deploy production to new live cluster

- README.md
- cla_backend/settings/.example.local.py
> Jo update readme

- .circleci/config.yml
Remove live-1 staging deployment
> LGA-1949 - Remove live-1 staging deployment

- README.md
The deployment instructions in the readme are out of date and needed updating.
> updated readme instructions for deploying

- .circleci/config.yml
remove production_deploy_live1 from circle config
> LGA-1951 CLA Backend Production Live-1 Clean-up

- .circleci/define_build_environment_variables
removed the need for different hosts
> LGA 1952 host clean up

- helm_deploy/cla-backend/templates/ingress.yaml
Reverts ministryofjustice/cla_backend#770
> Revert "LGA-1933 - Remove deprecated extensions/v1beta1 ingress api version and use networking.k8s.io/v1"

- .circleci/config.yml
- helm_deploy/cla-backend/templates/ingress.yaml
Reverts ministryofjustice/cla_backend#771
Restore the ingress version update work
> LGA-1933 - Remove deprecated extensions/v1beta1 ingress api version and use networking.k8s.io/v1

- .circleci/config.yml
There are two lines that install helm in circle config and both need to be updated - only one was done in previous PR
Required.
> WIP-LGA-1933-correct-circleci

- .circleci/config.yml
- helm_deploy/cla-backend/templates/deployment.yaml
Update unit test database to postgres10
> LGA-2056 - Update deployment pipeline to use postgres10

- helm_deploy/cla-backend/templates/ingress.yaml
putting a WAF in monitor mode.
> LGA 2048 Implement WAF

- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values.yaml
Make production use migrated database
Make all environments use database values in the main values.yaml
> LGA-2064 - Update application to use migrated db

- docker/cla_backend.ini
- helm_deploy/cla-backend/values.yaml
added http-workers to increase to 5 from default of 1
> Add http-workers to UWSGI set up

- helm_deploy/cla-backend/templates/cron.yaml
Disabling multiple codes cron job seems to be creating lots of noise and errors in kibana. Investigating failure of frontend on production.
> Disable multiple codes cron job

- helm_deploy/cla-backend/templates/ingress.yaml
Required.
This slows down requests with large json bodies like during the provider csv upload coming from frontend
Related to https://github.com/ministryofjustice/cla_frontend/pull/820
> Disable modsecurity json parser

- .github/workflows/semgrep.yml
- cla_backend/apps/legalaid/fixtures/test_user_with_case.json
- Obi wan kenobi's reference amended UUID to be version 4.
- 
> Amendment to Obi Wan Kenobi

- cla_backend/apps/knowledgebase/fixtures/kb_from_knowledgebase.json
Add Housing Ombudsman to knowledge base article fixtures
Used for end to end tests
> LGA-1838 - Add Housing Ombudsman to knowledge base article fixtures

- cla_backend/urls.py
- docker/run.sh
- Added if conditions into docker run.sh directory to run collectstatic command needed in order to generate CSS and Javascript files for local testing. 
- Added static method to urlpatterns in order to build static files needed for docker image / local testing.
> Generate Static files for local development testing

- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
Reduce replica count for non-production environments
> LGA-2200 -Reduce replica count for non-production environments

- .circleci/config.yml
updated config for new python images
> LGA 1880 upgrade circleci images

- helm_deploy/cla-backend/templates/_helpers.tpl
Add service-name to apps allowed hosts
Required for https://github.com/ministryofjustice/cla_frontend/pull/832
> LGA-2251 - Add service-name to apps allowed hosts

- cla_backend/apps/complaints/views.py
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/tests/test_utils.py
- cla_backend/settings/.example.local.py
- cla_backend/settings/base.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- Update Django 1.7.9 to 17.10 
Flake8 and Black ran to tidy up code.
[LGA-1770](https://dsdmoj.atlassian.net/browse/LGA-1770)
> Linting and Django Upgrade to 1.7.10

- helm_deploy/cla-backend-migration/templates/deployment.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
Migrations and database updates for cla_backend to us database 11
> LGA 2162 & LGA 2161 Updating deployment.yaml for database migration from 10 to 11

- helm_deploy/cla-backend/values-staging.yaml
update staging values to temporarily include database-11 during the migration
> LGA-2164 Update staging to use database 11 

- bin/create_db.sh
- bin/post_update_tasks.sh
- helm_deploy/cla-backend/templates/create-db.yaml
- helm_deploy/cla-backend/templates/post-update-worker.yaml
> LGA-2222: Update oauth package

- cla_backend/apps/cla_butler/management/commands/housekeeping.py
- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/test_tasks.py
amended task so instead of deleting tasks over two years, it waits till they are three years old and do not have a specific outcome_code.
I amended/added unit tests for the task.
> LGA 2213 Delete old/unneeded cases

- helm_deploy/cla-backend/values.yaml
Allow migration of database 10 to database 11 within production.
> LGA-2171 updating values.yaml with database-11 config

- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- requirements/source/requirements-dev.in
> LGA-2292: Apply (non-django) recommended package updates

- cla_backend/apps/cla_butler/management/commands/diversity_data_check.py
- cla_backend/apps/cla_butler/migrations/0001_initial.py
- cla_backend/apps/cla_butler/models.py
- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/mixins.py
- cla_backend/apps/cla_butler/tests/test_command.py
- cla_backend/apps/cla_butler/tests/test_models.py
- cla_backend/apps/cla_butler/tests/test_tasks.py
- docker-compose.yaml
Add celery task to decrypt diversity data with current private key and log whether that was a success
Add command to schedule celery task to decrypt diversity data
Add rabbitmq as an additional docker compose service
Add celery workers as an additional docker compose service
> LGA-2415 confirm diversity data encryption

- .circleci/config.yml
Restore training deployment for master
> Restore training deployment for master

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/complaints/models.py
- cla_backend/apps/diagnosis/graph.py
- cla_backend/apps/legalaid/management/commands/recalculate_assigned_out_of_hours.py
- cla_backend/apps/legalaid/tests/views/mixins/case_api.py
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/views.py
- cla_backend/settings/base.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- requirements/source/requirements-testing.in
This reverts commit e47f663e65890396a0174aaad2d8120df2b6b590.
Required.
> Revert "LGA-1777 django upgrade 1 8 19 (#914)"

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/complaints/models.py
- cla_backend/apps/diagnosis/graph.py
- cla_backend/apps/legalaid/management/commands/recalculate_assigned_out_of_hours.py
- cla_backend/apps/legalaid/tests/test_timezones.py
- cla_backend/apps/legalaid/tests/views/mixins/case_api.py
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/views.py
- cla_backend/settings/base.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- requirements/source/requirements-testing.in
Work had been completed on 
- https://github.com/ministryofjustice/cla_backend/pull/914
This includes the update to Django 1.8.19, the update to DRF 0.3.1 and the fix for celery when upgrading to Django 1.8.19
This work can now be deployed.
This branch needed rebasing due to other changes to cla_backend
1. Merge changes to staging and training and check the backend-worker pods start up correctly - there is no need to take snapshots of these databases. If we need to rollback we can use a database from the auto generated snapshots.
2. Put [CLA_Public](https://github.com/ministryofjustice/cla_public) and [CLA_Frontend](https://github.com/ministryofjustice/cla_frontend) applications into maintenance mode using these [instructions](https://dsdmoj.atlassian.net/wiki/spaces/laagetaccess/pages/441 …
> LGA-2419: Deploy LGA 1777 and LGA 1797 

- helm_deploy/cla-backend/values-staging.yaml
Updates database values in cla-backend/values-staging.yaml to use database-14
> LGA-2511 update staging to use database 14

- helm_deploy/cla-backend/values-training.yaml
Updates database values in cla-backend/values-training.yaml to use database-14
> LGA-2513 add database-14 to values-training.yaml

- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/checker/tests/api/test_eligibility_check_api.py
- cla_backend/apps/legalaid/tests/views/mixins/eligibility_check_api.py
Updated PartnerPersonSerializer to allow the frontend to send null Partner income.
> LGA 2603 SP Save partner finances

- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values.yaml
Updates the value.yaml file to point to the Database-14 rds instance. As the values.yaml file is set as the default value, these variables are removed from the other value.yaml files (static-uat, staging, training)
> LGA-2514 update value.yaml files

- cla_backend/apps/reports/api.py
- cla_backend/apps/reports/tasks.py
Only include referrer url path parts if its not none
Order the exports list in ascending order
> Reason for contacting report - Only include referrer url path parts if its not none

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MIExtractByOutcomeExtended.sql
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
Copied MICaseExtract and made MICaseExtractExtend, this adds on notes and provider notes, as this could affect the length of the report running time and anyone who uses the original report.
> LGA 2664 Extend MICaseExtract with notes and provider notes

- helm_deploy/cla-backend/templates/deployment.yaml
> LGA-2518 - Upgrade UAT database to 14

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/CaseDemographicsReport.sql
- cla_backend/apps/reports/sql/MIExtractByOutcomeExtended.sql
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
This is a modified version of the case by outcome.
This still uses password for diversity data and returns extra geo data and un needed columns have been reduced.
> LGA 2685 - Case demographic report

- cla_backend/apps/checker/models.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/tests/test_reports.py
Extend reason for contacting report to include count of records, with cases and without cases
> LGA-2695 - Extend reason for contacting report to include count of records, with and without cases

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/ReasonsForContactingReportDisaggregated.sql
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
Add in a new report for disaggregated reasons for contacting
> Add in sql to generate report

- helm_deploy/cla-backend/templates/cron.yaml
- Changes remove-expired-reports schedule
- Removes comments from `cron.yaml`
> LGA 2715 Change remove expired reports schedule

- .gitignore
- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/settings/base.py
Add skeleton calls to cfe-civil main UAT
> LEP-431 Skeleton call to cfe-civil

- .github/workflows/semgrep.yml
- .gitignore
Make good builds have a green tick rather than a red cross by upgrading semgrep
> upgrade semgrep to avoid continual red builds

- .gitignore
- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/property.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_property.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Add property translator to cfe-civil integration
> LEP-439 property translator

- cla_backend/apps/checker/views.py
- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- setup.cfg
Logging of CFE request and response, to help analyse CFE requests
> LEP-448 Add add logging

- cla_backend/libs/eligibility_calculator/cfe_civil/conversions.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
Remove duplication from translate_savings method
> Remove duplication in translate_savings code

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/age.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_age.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Translate under18 and over 60 into ages for cfe-civil
> Lep 443 age translator

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/applicant.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_applicant.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Translate CLA ->  `facts -> on_passported_benefits` to CFE_CIVIL ->` applicant -> receives_qualifying_benefit`
JIRA: https://dsdmoj.atlassian.net/browse/LEP-440
> LEP-440 Translate on_passported_benefits

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/dependants.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_dependants.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Add translator for dependants.
Adds a CfeResponse class that can be extended to interpret the cfe civil result
> LEP-434 dependants translator

- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_income.py
Refactor. This way seems marginally more straightforward - what do you think @ripan? I was not a fan of creating a list with Nones in and then a step to remove them.
> LEP-435 refactor

- cla_backend/libs/eligibility_calculator/calculator.py
The idea has been for detailed logging to be kept to DEBUG level, but this one slipped through before.
> Logging of CFE Request is suppressed

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/deductions.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_deductions.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
> Lep 436 deductions translator

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Enable passported non-partner cases through  CFE rather than legacy_check()
> Lep 455 passported through cfe

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_employment.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
> LEP-459 use cfe result for all non partner cases

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
This is an alternative path to https://github.com/ministryofjustice/cla_backend/pull/1062
> LEP-456 "section_complete" logic is centralized

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
- cla_backend/settings/base.py
Adds disputed savings into the request mapping
> Lep-445 disputed savings

- cla_backend/apps/diagnosis/data/checker-graph.graphml
- cla_backend/apps/diagnosis/data/checker-graph.graphml.tpl
- cla_backend/apps/diagnosis/tests/test_graph.py
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
Update checker diagnosis graph to flag hlpas categories
> LGA-2920 - Update checker diagnosis graph to flag hlpas categories

- cla_backend/libs/eligibility_calculator/calculator.py
> LEP-468 Log differences between CFE and legacy checker

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
https://dsdmoj.atlassian.net/browse/LEP-470
> LEP-470 cla_public cases with any benefits, but not Child Benefit, are always treated as eligible

- bin/database-migration/Dockerfile
Revert dockerfile change which is not part of the cfe-integration work
> revert dockerfile change

- cla_backend/settings/base.py
- cla_backend/settings/circle.py
- helm_deploy/cla-backend/values-dev.yaml
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-cfe.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
Vary CFE Civil instance for different environments
> Lep 460 vary cfe between environments

- cla_backend/libs/eligibility_calculator/calculator.py
Remove hard-coded section as will be filled in dynamically
> remove default applicant section

- cla_backend/libs/eligibility_calculator/calculator.py
Local testing it and the request shows up in the CFE request logs (staging in my case)
> Set the User-Agent so CFE can recognize CLA requests

- cla_backend/apps/diagnosis/data/graph.graphml
- cla_backend/apps/diagnosis/data/graph.graphml.tpl
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
Amend the italic text on CLA_Frontend to remove regular expression
> Update expression to remove regular expression

- cla_backend/assets/admin/js/ReportTask.js
- cla_backend/settings/base.py
- cla_backend/templates/admin/reports/base.html
- Adds the AWS S3 Bucket to the list of allowed script sources.
- Adds a CSRF Token to the delete request of report forms.
> Update csrf token and script src

- cla_backend/apps/reports/sql/CaseDemographicsReport.sql
Fixes incorrect date thresholds in the updated Case Demographic Report
> Fixed incorrect date thresholds

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/CaseDemographicsReport.sql
- cla_backend/apps/reports/sql/MinimalCaseDemographicsReport.sql
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
- Alters the Case Demographic report so only the latest log event is selecting, reducing the number of rows extracted.
> LGA 3011 Case demographics report not producing full dataset

- cla_backend/apps/legalaid/migrations/0035_grant_anon_user_permissions.py
- cla_backend/apps/legalaid/models.py
Adds in the PII fields to analytics
> Add in PII

- cla_backend/apps/legalaid/models.py
- helm_deploy/cla-backend/values-dev.yaml
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
- Enables Metabase in the production environment.
- Adds NI Number of the list of PII Data.
- Removes ID from the list of PII Data as this is the primary key for this table in the database.
> LGA 3039: Setup Metabase deployment in cla backend production

- helm_deploy/cla-backend/values.yaml
- Adds the IP Range for the Ministry of Justice Official technology platform to the IP whitelist for Fox Admin.
> LGA-3141: Add MoJ Official IP range to whitelist

- .circleci/config.yml
Disable snyk auto deployment to uat
> LGA-3167 - Disable snyk auto deployment to uat

- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/test_cleanup.py
- Removes any archived cases that were last modified over 3 years ago by adding this as a step to the Housekeeping CronJob, which is run every day at 5AM.
> LGA-3291: Cleanup Historic Case Archive

- .circleci/config.yml
- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/tests/api/test_eligibility_check_api.py
- cla_backend/apps/legalaid/constants.py
- cla_backend/apps/legalaid/migrations/0037_eligibilitycheck_disregard_selection.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/tests/test_models.py
- cla_backend/apps/legalaid/tests/views/mixins/eligibility_check_api.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
Adds a new column and serialiser for disregard selection. The requirements file will need to be updated to reflect the most recent cla common changes before it is merged.
[- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"](https://dsdmoj.atlassian.net/browse/LGA-3323)
> LGA 3323 MTR Disregard changes

- .circleci/config.yml
- helm_deploy/cla-backend/templates/pdb.yaml
- helm_deploy/cla-backend/values-dev.yaml
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
> LGA-3655 - Add pod disruption budget

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/WebContactCases.sql
- cla_backend/apps/reports/sql/web_contact_cases.sql
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/utils.py
- cla_backend/apps/reports/views.py
- run_local.sh
Add sql for web contact cases report.
> WIP - LGA-3687 - Add sql for web contact cases report
