- cla_backend/apps/checker/serializers.py
- cla_backend/apps/checker/tests/api/test_case_api.py
added because CLA public is now going to be supplying third party details along with contact details
> add Third Party support to CLA backend

- cla_backend/__init__.py
- cla_backend/apps/reports/tasks.py
- cla_backend/apps/reports/utils.py
- cla_backend/celery.py
- cla_backend/settings/.example.local.py
- cla_backend/settings/base.py
- docker/celery.service
- requirements/base.txt
adding celery because we have a log running db export task we don't want to run during a request,
this celery confguration falls back to running the task in procress if celery broker is not set up so local development isn't annoying.
I have also created a sentry test task so we can see that celery errors get to sentry.
> Add Celery

- cla_backend/apps/reports/views.py
previously, a server error was sent in response to an incorrect key for encrypted diversity data, now an error message is presented
e.g. see http://sentry.prod.cla.dsd.io:8080/default/default/group/312/
[Fixes #95523210]
> MI report export fix for incorrect password

- cla_backend/apps/checker/admin.py
- cla_backend/apps/checker/migrations/0001_initial.py
- cla_backend/apps/checker/models.py
- cla_backend/apps/checker/serializers.py
- cla_backend/apps/checker/tests/api/test_reasons_for_contacting_api.py
- cla_backend/apps/checker/tests/mommy_recipes.py
- cla_backend/apps/checker/urls.py
- cla_backend/apps/checker/views.py
- cla_backend/apps/core/fixtures/initial_groups.json
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/serializers.py
- cla_backend/apps/legalaid/views.py
- cla_backend/templates/admin/checker/reasonforcontacting/change_list.html
- requirements/base.txt
in public site, when a user drops out of the scope/means test flow, they are presented with a form to find out why they want to get in touch. the form was previously sent to zendesk
[Fixes #96775836]
depends on [cla_common#31](https://github.com/ministryofjustice/cla_common/pull/31)
> reasons for contacting can now be stored in DB

- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/views.py
- cla_backend/apps/complaints/forms.py
• a single case (i.e. its one-to-one EOD) can have multiple open complaints
• cases API reports the open complaint count
> complaints updates

- README.rst
- psql will error if there's no db with the same name as the username
- maybe best to have the user connect to one of the template dbs
> psql will take username as default- could error if no db

- cla_backend/apps/checker/tests/api/test_eligibility_check_api.py
- cla_backend/apps/checker/views.py
- cla_backend/apps/core/drf/mixins.py
- cla_backend/apps/timer/models.py
- add getter for case ref from eligibility check on puyblic checker api
- aims to fix error of broken requests from public when saving a case
> Fix Sentry errors

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Date Closed' cannot be from the current month
- 'Time Spent' - has to be in 6 minute increments. If Determination code is present, it has to be in 6 minute increments up to 18 minutes. In Education/Housing/Debt/Family it has to be in 6 minute increments up to 18 minutes. In Discrimination it has to be in 6 minute increments up to 42 minutes.
- 'Determination' - when DVCA is entered it has to be a Family case.
> Add validation rules to csv upload

- cla_backend/settings/jenkins.py
As Django test runner does not support replica DBs (MIRROR setting
just redirects to use the other connection), change the default
connection to use the custom engine when running in jenkins.
Tests fail during BST due to the connection not being UTC if using
the default postgres engine.
> Use custom reports backend for test DB in Jenkins

- cla_backend/apps/cla_butler/management/commands/housekeeping.py
- cla_backend/apps/cla_butler/stack.py
- cla_backend/apps/cla_butler/tasks.py
- docker/cla_backend.ini
- requirements/base.txt
Interrogate stack metadata to determine if running on the first instance of the ASG,
and if so perform housekeeping.
Also cease backing up deleted data to disk as it is unsustainable.
> Run housekeeping on a regular schedule on the first instance

- cla_backend/apps/call_centre/views.py
- cla_backend/apps/legalaid/migrations/0018_auto_20180425_1558.py
- cla_backend/apps/legalaid/views.py
Trigram indexes can be helpful when making database queries of the form
`LIKE '%term%'` which do not use normal queries due to the leading
wildcard.
However, doing an `OR` between columns on two different tables in an
`OUTER JOIN` does not hit these indexes anyway, so it was necessary to
change the query to using `UNION` and `INTERSECT` to combine the
search terms instead. This part of the query is done in a `TEMPORARY VIEW`
which is then `INNER JOIN`ed to the rest of the query to filter the cases.
> Add trigram indexes to case search fields and restructure query to use them

- cla_backend/apps/cla_butler/management/commands/housekeeping.py
- cla_backend/apps/cla_butler/stack.py
Temporarily remove AWS credentials from environment in order to
use the default IAM role for the instance instead of the S3 storage
user.
> Fix bugs with running of housekeeping task

- README.md
The develop branch doesn't exist anymore. This pull request updates the badge to refer to `master` branch.
Nothing.
> Circle CI badge refers to master branch

- cla_backend/apps/legalaid/views.py
This pull request fixes an error where anything entered into the search bar in the case handling system that was not an ASCII character, such as the fancy apostrophe in Mark O’Brien or when searching with the "£" sign, would result in a 500 error code and display the error message below. 
_UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 1: ordinal not in range(128)_
This was fixed by simply add 'u' where the search string was being formatted so that it was able to handle  non-ASCII characters such as these. 
> Fix unicode issue in the case handling system

- cla_backend/apps/cla_butler/management/commands/monitor_multiple_outcome_codes.py
- docker/cla_backend.ini
Check for multiple outcome codes occurring today (since 00:00)
The included whitelist is from outcomes designated as strictly once in the spreadsheet. May need adjusting.
> LGA-294 Check for multiple outcome codes occurring today

- cla_backend/apps/cla_butler/management/commands/monitor_missing_outcome_codes.py
- cla_backend/settings/base.py
- cla_backend/settings/docker.py
- docker/cla_backend.ini
Move invocation of `monitor_missing_outcome_codes` script to uW, inside the container
Reconfigure uW to log to stdout
Add Sentry as a log handler, set to error level
Adjust logging in monitor_missing_outcome_codes
Use simple formatter for console logging to avoid nested logstash
> LGA-384 uW cron

- cla_backend/apps/cla_eventlog/models.py
Blindly log each time an outcome Log object is saved.
> LGA-293 Log every time an outcome Log object is saved

- cla_backend/apps/legalaid/tests/test_utils.py
- cla_backend/apps/legalaid/utils/sla.py
- cla_backend/settings/base.py
Add custom operator hour tests
Use OpeningHours.time_slots
Set custom working hours for Christmas Eve and New Year's Eve 2018.
Switch to use the `time_slots` method of the `OpeningHours` class that respects custom working hours.
(`cla_common` needs some careful tending to)
> LGA-380 Reduced Xmas Working Hours

- README.md
- pyproject.toml
- requirements/dev.txt
- setup.cfg
Introduce configs for flake8 and Black. flake8 monitors style and complexity violations while Black is a strict and opinionated Python formatter.
Make mention in README
Rename local.txt requirements to dev.txt
> Add modern Python code quality tools

- requirements/base.txt
Updates `cla_common` requirement to latest tagged release: `0.3.0`
Newest version of `cla_common`, fixes versioning error in old release
No code changes applicable to cla_backend
This will require changes in PR 494 merged before tests pass.
> Use cla_common==0.3.0

- .circleci/config.yml
- Dockerfile
In CircleCI, the test jobs are currently failing
https://www.python.org/dev/peps/pep-0517/ causes problems with cla_common and pip 19 uses it by default.
Using --no-use-pep517 does not work with pip install -r requirements.txt. The workaround is to downgrade to the previous version of pip.
We can upgrade to the next pip version if cla_common is made compatible with https://www.python.org/dev/peps/pep-0517/.
Same as https://github.com/ministryofjustice/cla_public/pull/800
> Use pip version 18

- cla_backend/apps/status/healthchecks.py
- cla_backend/apps/status/tests/healthchecks_tests.py
- cla_backend/settings/base.py
Send notification to #cla-alerts slack channel when disk space available is below 2% on any of the cla_backend servers
the disk space health checks have been added to the list of health checks carried out using the moj_irat library. 
Currently the Elastic Load Balancers carry the health checks trigger the relevant cloud watch alarms, these then send a notification to the SNS topics which in turn trigger an AWS Lambda. There are two SNS topics one for low priority and another for high priority notifications.
The current lambdas were sending the alerts to the #high-priority-alerts or #low-priority-alerts slack channel. These were not modified as I am not currently sure where else they are used.
Outside of this PR, a new SNS topic CloudWatchToSlackCLAHealthChecks was created along with a new …
> LGA-434 - Alert when cla_backend is close to running out of disk space

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- Add base test data for 2018 contract tests
- Update `test_validator_fafa_determination_code_is_valid` to use new base
> Add some base test data for 2018 contract tests

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- Factors out all the validation steps 2018 contract tests have in common.
- Further updates Said's already updated `test_validator_housing_outcome_code_haa_is_valid`
> LGA-242 Even simpler 2018 contract tests

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
[LGA-33: New outcome codes for discrimination](https://dsdmoj.atlassian.net/browse/LGA-230) 
This pull request creates a new outcome code for discrimination and places it inside the 2018 category spec, so that means that it will only be updated when the 2018 contract is put in motion. It also creates a tests that ensures that when this new code is included in a CSV file, and uploaded into the Case Handling System, it is able to be validated by the ProviderCSVValidator class.
> Outcome code for discrimination

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
[LGA-239: New family outcome code 2 ](https://dsdmoj.atlassian.net/browse/LGA-239)
This pull request creates a new outcome code for family code FAB and places it inside the 2018 category spec, so that means that it will only be updated when the 2018 contract is put in motion. It also creates a tests that ensures that when this new code is included in a CSV file, and uploaded into the Case Handling System, it is able to be validated by the ProviderCSVValidator class.
> Outcome code for family 2

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
[New determination code EXEM](https://dsdmoj.atlassian.net/browse/LGA-179)
This pull request creates a new determination code, EXEM and places it inside the 2018 category spec so that means that it will only be updated when the 2018 contract is put in motion.
> Add a test and new code EXEM to the contract_2018_determination_codes

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Add fixed fee columns to 2018 validators
- Validate fixed fee amount is present and truthy when fixed fee code is DF, LF, or HF
- Test fixed fee amount present and missing
- Addresses `LGA-251 New fixed fee code - Determination Fee - DF` and `LGA-252 New fixed fee code - Lower Fixed Fee - LF`
Simplifies and better separates building 2013 and 2018 validators.
> LGA-431 Fixed Fee amount

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- cla_backend/settings/base.py
- Add MR, HM, and NA fixed fee codes, validators, and tests
- Refactor old 2013 tests to override with only a delta of pertinent changes
- Use more accessors to return the right validators dynamically
- But only assemble three versions of our validators once
- Fork a handful of tests for CONTRACT_2018_ENABLED True and False
- Rework 2013 validators to support new format when CONTRACT_2018_ENABLED
> LGA-256 LGA-257 LGA-258 Fixed Fee MR, HM, and NA

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Validate eligibility codes for 2018 contract rows against supplied Fixed Fees.
- Split existing tests into 2018-contract-toggle-off and 2018-toggle-on
> LGA-261 Validate eligibility codes

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Validate signposting code if one has been entered
- Validate signposting code has been entered for a subset of outcome codes
Merge PR #543 `feature/eligibility-codes-validation` first. This is a child branch.
> LGA-442 Validate signposting code

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Validate DF fixed fee code only used in conjunction with a determination code
- Fix `_test_generated_2018_contract_row_validate_fails` to also fail if no expected exception raised
> LGA-263 Validate determination code present for DF fixed fee

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- Validates HF (higher fee) and LF (lower fee) fixed fee codes are used in conjunction with the correct amount of time spent
- Validation was introduced previously alongside the HF and LF codes in previous work. This branch updates validation messages, tweaks the time spent boundaries after clarification from the business, and adjusts tests
> LGA-265 LGA-266 Validate HF and LF fixed fee codes

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Adds further validation for `HF`, `HR`, and `HM` fixed fee codes:
- That the correct eligibility codes are use with `HF`
- That time spent is >= 900 for `HR`
- That Matter Type 1 is `FAMY` for `HM`
> LGA-264, LGA-267, LGA-269 HF, HR, HM fixed fee validation

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Improve message for invalid outcome codes
Validation was already in place but returned unreadable error message, so has been replaced with this new method.
> LGA-386 Improve outcome code validation message

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Amend PR #556 to allow `0` as a valid Fixed Fee Amount.
> LGA-492 Fixed fee amount validation rule zero amount allowed

- cla_backend/apps/cla_eventlog/models.py
- cla_backend/apps/cla_eventlog/tests/test_events.py
- Allow same day consecutive outcome codes if notes field differs
- Add ConsecutiveOutcomeCodesTestCase
> LGA-568 Allow same day consecutive outcome codes with differing notes

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Fixes the issue with 2018 Discrimination Contracts not validating due to the matter_type1 field not being provided.
2018 Discrimination rows can have NA as the value for the fixed fee code. These were being incorrectly reported as invalid on UAT
> LGA-618 - Fix 2018 Discrimination Contracts not applying

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/contracts.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
- cla_backend/apps/status/urls.py
- cla_backend/apps/status/views.py
- cla_backend/settings/base.py
Determine whether a case is a 2018 Education case.
Fix existing tests to work with the NA code for  2018 Education cases
Add the state of the 2018 Contract changes flag to the ping output
> LGA-608 - Determine whether a case is 2018 Education case

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
Added test for error message when NA fix fee code is provided for 2018 cases that are not Discrimination or Education
The logic to generate the error message under right conditions already existed but was just missing tests
> LGA-609 - Add test for error message for NA fix fee code

- cla_backend/apps/cla_provider/tests/api/test_csvupload_api.py
- cla_backend/apps/legalaid/utils/csvupload/validators.py
Add T and V Eligibility codes to Low Fee Fixed Fee Code validation
> LGA-625 - The eligibility code must be one of the valid codes - S, T, V, W, X, Z

- cla_backend/apps/legalaid/utils/csvupload/validators.py
Check if val is truthy before use in validate_not_present.
> LGA-619 - Check if val is truthy before use in validate_not_present

- cla_backend/settings/base.py
Turn on 2018 contract changes by default flag to on.
> LGA-586 - Turn on 2018 contract changes by default

- .dockerignore
- Dockerfile
- docker/celery.service
- docker/cla_backend.ini
- docker/entrypoint.sh
- docker/nginx.conf
- docker/nginx.service
- docker/supervisord-services.ini
- docker/uwsgi.service
Switches the Docker image to use Alpine Linux and pre-installed nginx and uwsgi, effectively reducing the image size by ~60%.
```
.../laa-get-access/laa-cla-backend    shrink-image.b65eee4           470MB
.../laa-get-access/laa-cla-backend    master                        1.27GB
```
The current image is 1.27GB in size. This new version that is based on the official Alpine Linux/Python 2.7 image is around ~480MB big.
The reduced image size will
* speed up builds for this repository (5-6 minutes vs the previous 9-10 minutes).
* speed up running the [end-to-end tests](https://github.com/ministryofjustice/laa-cla-e2e-tests)
* Since the image replaced the `/sbin/my_init` supervision process, `supervisord` was introduced as a replacement. Consequently, the `*.service` files were replaced with a …
> Shrink Docker image

- Dockerfile
Attempts to fix the issue preventing users from uploading and downloading large files.
**Explicitly allow www-data access to /var/tmp/nginx**
In Alpine Linux, the default directory by used by nginx is `/var/tmp/nginx`, compared to Ubuntu's `/var/lib/nginx`.
Currently, users cannot upload and download files due to permission issues which are most likely caused by `/var/tmp/nginx` not having correct permissions.
This change was not picked up when I migrated the image from Ubuntu to Alpine and needs amending.
Alternatively, we could run the nginx process as the `nginx` user, but that would need more changes which I would like to defer now.
**Remove default nginx configuration**
There is a default configuration in Alpine which we do not need and can be removed.
**Collapse layers changing …
> LGA-651: Allow users to upload and download files

- docker/entrypoint.sh
Add --noinput flag to migrations so that it doesn't hang during deployment
Migrations are run as part of the container entrpoint commans. Without the --noinput flag the migrate command will hang waiting for input, this will cause the deployment to fail as the container does not come up successfully.
- [] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"
> Add --noinput flag to migrations so that it doesn't hang during deployment

- .circleci/config.yml
Make circleci build job dependant on test job
Currently circleci continues with the build job even when the test job fails, this could lead a accidentally deploying a release with failing tests. This PR ensures tests pass before the build of release image is started.
> LGA-691 - Make circleci build job dependant on test job

- .circleci/config.yml
Skipping this step means we don't have to install postgres on the first container (the
python one), which was causing the following error during build
```#!/bin/bash -eo pipefail
sudo apt-get install postgresql-client-9.6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package postgresql-client-9.6
E: Couldn't find any package by glob 'postgresql-client-9.6'
E: Couldn't find any package by regex 'postgresql-client-9.6'
Exited with code 100
```
Running the Circle job with two docker images isn't doing what we probably think it is, specifically in that all `steps` are run on the primary container (the first one listed). This is why we were needing to install postgres as a step, when we already had a postgres sidecar …
> LGA-717 - Skip installation of pgrypto extension

- cla_backend/apps/call_centre/admin/__init__.py
- cla_backend/apps/call_centre/admin/forms.py
- cla_backend/apps/call_centre/management/commands/cla_superuser_organisation_perms.py
- cla_backend/apps/call_centre/management/commands/create_and_assign_agilisys_organisation.py
- cla_backend/apps/call_centre/migrations/0003_auto_20190726_1200.py
- cla_backend/apps/call_centre/migrations/0003_auto_20190729_1416.py
- cla_backend/apps/call_centre/models.py
- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/tests/admin/test_views.py
- cla_backend/apps/call_centre/tests/api/test_user_api.py
- cla_backend/apps/call_centre/tests/mommy_recipes.py
- cla_backend/apps/call_centre/tests/test_commands.py
- cla_backend/apps/call_centre/tests/test_models.py
- cla_backend/apps/call_centre/views.py
Creates new Organisation model
- Added organisation foreign key to Operator model
- Added django command to auto create Agilisys organisation and assign existing operators to organisation
- Restricted organisation operator managers to only seeing operators in their organisation
- Automatically add newly created operator to the same organisation as the operator manager that is creating them
- Added command to assign CLA Superusers 'Can add organisation' and 'Can change organisation' permissions
Associate operators with an organisation so that content can be restricted to a specific organisation
> LGA-716 - Associate operators with an organisation

- .circleci/config.yml
- README.md
- cla_backend/apps/core/testing.py
- cla_backend/settings/circle.py
- requirements/testing.txt
Wraps test running in `coverage`
Stores the output on circleci as artifacts
Sends coverage results to coveralls.io
Adds a coveralls badge to the readme
Generates and stores test metadata in xml format for CircleCI to monitor
No
> LGA-693 - Code coverage on circleci

- cla_backend/apps/call_centre/views.py
- cla_backend/apps/legalaid/management/commands/assign_existing_cases_to_organisation.py
- cla_backend/apps/legalaid/migrations/0022_case_organisation.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/tests/test_commands.py
- cla_backend/apps/legalaid/tests/test_models.py
Added new Case.organisation field
Added script to assign Case.organisation to Operator.Organisation
Assign cases organisation when a case is created
> LGA-715 - Assign organisation to cases

- docker/supervisord-services.ini
Re-enables the (mistakenly) disabled logs of subprocesses started by the supervisor process control system.
Please review commit-by-commit for details.
Our `uwsgi-cron` logs have disappeared since 9 July:
As it turns out, it was the first time #573 was deployed again to production (it was rolled back for some time). Unfortunately, the logs of our services were **disabled** with similar messages:
```
2019-09-13 07:33:35,150 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140244011103440 for <Subprocess at 140244011290568 with name uwsgi in state STARTING> (stderr)> (<type 'exceptions.IOError'>:[Errno 29] Invalid seek [/usr/lib/python2.7/site-packages/supervisor/supervisord.py|runforever|221] [/usr/lib/python2.7/site-packages/supervisor/dispatchers.py|handle_read_even …
```
> Re-enable missing logs

- cla_backend/apps/reports/sql/MISurveyExtract.sql
- cla_backend/apps/reports/tests/test_reports.py
Concatenate multiple organisations into comma separated list for organisation field in the mi survey DOM1 extract
> LGA-810 - Concatenate multiple organisations into comma separated list

- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/templates/call_centre/email/case_cb1_created.txt
- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/checker/serializers.py
- cla_backend/apps/checker/tests/api/test_case_api.py
- cla_backend/apps/legalaid/admin.py
- cla_backend/apps/legalaid/forms.py
- cla_backend/apps/legalaid/migrations/0022_case_callback_window_type.py
- cla_backend/apps/legalaid/migrations/0023_case_callback_window_type.py
- cla_backend/apps/legalaid/migrations/0024_default_to_half_hour_window.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/tests/test_models.py
- requirements/base.txt
Allows storing of callback times with the meaning of either a single time with an implicit window around it, or an explicit half hour window. Then provides this in serializers and in a property that calculates the correct representation of the time for the callback.
Accompanies changes to cla_backend and cla_public
Should be reviewed but not merged until we're ready to go live with the change
> LGA-731: Callback window changes

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/tests/test_reports.py
Fixes the date range check on the reports generation form when the date range crosses a date on which the clocks go back.
Adds some solid tests which always test the cases when the clocks go back or forward, rather than only testing the current dates, and which actually test the edges of the allowed date ranges.
> LGA-850 - Make date range check work when clocks go back

- cla_backend/apps/call_centre/tests/test_forms.py
Update bank holiday to be closer to todays date
2014 Bank holidays were removed from the bank holidays API https://github.com/alphagov/calendars/commit/c28e7b570c39a10f60d2ed13b85d477b9a60159e#diff-1569053def8d48383b565a3d2d505529
> Update bank holiday days to be closer to todays date

- .coveragerc
- cla_backend/apps/call_centre/forms.py
- cla_backend/apps/legalaid/tests/test_utils.py
- cla_backend/apps/legalaid/utils/sla.py
- cla_backend/settings/base.py
- cla_backend/settings/testing.py
- requirements/base.txt
Reduce callbacks to be booked between the hours of 9am-6pm on Christmas Eve New Years Eve 2019
Mock cla_common.call_centre_availability.current_datetime when running custom sla hours test during Christmas and New Years Eve
Previously the legalaid.tests.test_utils.SlaCustomBusinessHoursTestCase tests were set to use dates in the future as the operating hours could not be in the past as of https://github.com/ministryofjustice/cla_backend/pull/494 (also https://github.com/ministryofjustice/cla_backend/pull/493#issuecomment-451196319)
The problem with having those dates in the future is you cannot test this year Christmas / New years eve opening hours.
> LGA-892- 2019 Christmas Eve / New Years Eve Reduced Operating Hours

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
* Remove pushing images to Live-0 Cloud Platforms ECR repository
This project was pushing to old live-0 Cloud Platforms ECR repository which is no longer in use. Cloud platforms have removed all non-production namespaces on live-0 https://github.com/ministryofjustice/cloud-platform-environments/pull/1770
It seems the push to the ECR repository was added in anticipation of moving to kubernetes at the time. However the Cloud platforms environments have changed since the original work.
When this project does move to cloud platforms managed environment, the relevant repository can be added.
> Remove pushing images to Cloud Platforms ECR repository

- cla_backend/apps/legalaid/migrations/0026_safe_to_contact_remove_no_message.py
- cla_backend/apps/legalaid/tests/test_migrations.py
- requirements/base.txt
Remove NO_MESSAGE choice from safe_to_contact field choices
Migrate existing records with NO_MESSAGE to SAFE because CHS operators do not leave a message
Requires https://github.com/ministryofjustice/cla_frontend/pull/669
> LGA-876 - Remove NO_MESSAGE choice from safe_to_contact field choices

- cla_backend/apps/legalaid/migrations/0027_update_education_matter_type1_descriptions.py
Increment migration number to avoid conflict of migration files numbering.
The two files were developed in two branches and both started with 0026
> Increment migration number to avoid conflict of migration files numbering

- cla_backend/apps/call_centre/serializers.py
Adds the outcome description to the `Log` serializer, like is done on the `Case` serializer for the case list page.
> LGA-915 - Calculate event log description in serializer

- .circleci/config.yml
- .circleci/define_build_environment_variables
- .circleci/tag_and_push_docker_image
Reverts ministryofjustice/cla_backend#606
Update to push images to Live-1 ECR repo instead of Live-0
Removed hard coded values for ECR_DOCKER_REGISTRY, ECR_DOCKER_IMAGE and AWS_DEFAULT_REGION and moved values into environment variables
https://github.com/ministryofjustice/cloud-platform-environments/pull/1937 (merged)
> LGA-705 - Push images to ECR repository on Live-1

- cla_backend/settings/base.py
- requirements/base.txt
Use Django cache to cache bank holidays lookups
Requires https://github.com/ministryofjustice/cla_common/pull/91
The dependency on django cache for caching bank holidays has been removed cla_common.call_centre_availability. Now the dependency must be satisfied through the CacheAdapter class
https://github.com/ministryofjustice/cla_common/pull/91
> LGA-973 - Use Django cache to cache bank holidays lookups

- cla_backend/apps/reports/tasks.py
- cla_backend/apps/reports/tests/test_tasks.py
Reset the task last message at the start of task.run
Added `Check passphrase and try again` message when diversity passphrase is incorrect
Currently the OBIEE extracts seem to failing with the error message `An error occurred creating the zip file` however the extract seems to be downloadable.
https://docs.celeryproject.org/en/3.0/userguide/tasks.html#instantiation states that:
> A task is not instantiated for every request, but is registered in the task registry as a global instance.
So this means that the same instance of the OBIEEExportTask is being used to handle multiple exports which means unless explicitly reset instance properties such as `message` retain their values through multiple exports.
The current issue is cause by when one export fails due to a legitimate error such as …
> LGA-1046 - Reset the task last message at the start of task.run

- cla_backend/apps/legalaid/serializers.py
Make Case.exempt_user and Case.exempt_user_reason fields readonly
> LGA-1238 - Make Case.exempt_user and Case.exempt_user_reason fields readonly

- .circleci/config.yml
Make epic/LGA-959-kubernetes branch deployable to production
> LGA-1373 make k8s epic branch deployable to production

- cla_backend/apps/cla_butler/management/commands/housekeeping.py
- cla_backend/apps/cla_butler/management/commands/monitor_missing_outcome_codes.py
- cla_backend/apps/cla_butler/management/commands/monitor_multiple_outcome_codes.py
- cla_backend/apps/cla_butler/management/commands/reverthousekeeping.py
- docker/cla_backend.ini
- helm_deploy/cla-backend/templates/cron.yaml
Move cronjobs from running inside of the uswgi process to Kubernetes cronjobs
Removed checking of EC2 instance inside cla_butler management commands
There were additional checks being done to stop the cla_butler management commands running on the second EC2 instance. These checks have now been removed because we are no longer using EC2 and concurrency of the process running these jobs now is set to 1 and controlled (it's not running inside multiple uwsgi process)
> LGA-1368 migrate cron jobs

- .gitignore
- cla_backend/apps/cla_provider/tests/test_helpers.py
- cla_backend/settings/testing.py
Adds tests to demonstrate the allocation process across days (where currently only cases from the same day are taken into account). Skips the test that would require this to be changed.
Follows @said-moj's fix of other tests in order to get a previous test working, and reduces its volume from 8000 cases to 80 for practicality and because there's no reason to have so many.
> LGA-1350 - Allocation tests

- cla_backend/apps/call_centre/forms.py
- cla_backend/apps/call_centre/tests/test_forms.py
Allows callbacks to be scheduled in the current and next callback windows, in addition to all future windows as normal.
Requires corresponding frontend change in order to provide its benefit. cla_public already enforces stricter rules than this (it doesn't allow callbacks within 2 hours), so its behaviour won't be affected.
> LGA-1383 - Remove call back scheduling delay

- .circleci/define_build_environment_variables
- bin/production_deploy.sh
- helm_deploy/cla-backend/templates/ingress.yaml
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
- Use PRODUCTION_HOST circle env var that contains the production fox admin domain
- Add secret name that contains the tls secret for the fox admin domain
- Removed unused .Values.ingress.tls config
This should be merged just before switching to the kubernetes application
> LGA-1370 - Create fox admin ingress

- .circleci/config.yml
- bin/local_deploy.sh
- bin/pingdom_ips.py
- bin/production_deploy.sh
- bin/staging_deploy.sh
- bin/uat_deploy.sh
- helm_deploy/cla-backend/templates/_helpers.tpl
- helm_deploy/cla-backend/values-dev.yaml
Add Pingdom IP addresses to the whitelist
Pingdom servers IP addresses will vary and can't be part of the static whitelist.
This adds some extra steps to the circleci job to get those dynamic pingdom IPs and add it as a variable to helm  install
> LGA-1432 - Add pingdom dynamic IP address to whitelist

- cla_backend/settings/base.py
Fixes static files, which come from s3, by setting AWS_QUERYSTRING_AUTH to False.
Static files bucket is public so doesn't need signed urls. As they'd
expire, and because it makes paths harder to naively construct, we're
much better off without (right now, the signature breaks our image paths
and turning it off fixes them).
The reports do not use signed urls for access, so are not affected by
this
> LGA-1433 - Fix admin images

- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/cla_provider/tests/test_helpers.py
Removes the constraint that only considers the current day when deciding whether to balance up the allocations or allocate randomly.
There is already a constraint in there to limit it to allocations since the weightings were changed.
> LGA-1396 - Fix allocations across days

- .circleci/define_build_environment_variables
- bin/production_deploy.sh
- bin/staging_deploy.sh
Sets $RELEASE_NAME to 'cla-backend' on staging and production, so that
the Helm chart is consistently named and therefore future releases
update the chart regardless of branch name (although the branch name
will usually be consistent for these deploy types anyway).
Removes the fullnameOverride on staging and production, as we don't want
or need our Kubernetes objects to have branch-specific names - again,
that's a UAT environment thing allowing multiple releases to exist at
once, and is detrimental on staging and production for similar reasons
to the release naming. Without the override, these releases will default
to being called 'cla-backend', from the Chart.yaml definition, and this
is what will be the basis of the naming of the deployments, ingresses
etc created for the release. …
> LGA-1434 - Stop non-UAT releases using unique names

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/checker/tests/api/test_case_api.py
- cla_backend/apps/legalaid/tests/test_helpers.py
- requirements/base.txt
cla_common has been updated with [new operator hours](https://github.com/ministryofjustice/cla_common/pull/98)
This PR updates cla_backend to use that version of the library, and thus the new hours. It should not be merged until we're ready to deploy this behavioural change.
> LGA-1424 - Update cla_common

- bin/staging_deploy.sh
- helm_deploy/cla-backend/templates/NOTES.txt
- helm_deploy/cla-backend/values-staging.yaml
- helm_deploy/cla-backend/values-uat.yaml
Added certificate for new staging domain
- Cloud platforms PR to add certificate https://github.com/ministryofjustice/cloud-platform-environments/pull/3203/files
- The ingress hostname is set in the bin/<environment>_deploy.sh scripts and stored in .Values.host
- Removed redundant Values.ingress.hosts and Values.ingress.paths as the .Values.host is set in the deploy script and used frequently
> LGA-1458 Added certificate for new staging domain

- docker/cla_backend.ini
- helm_deploy/cla-backend/templates/deployment.yaml
Add preStop lifecycle hook and terminationGracePeriod to allow enough time for uwsgi finish processing requests
Changes explained:
- **die-on-term** - respect the convention of shutting down the instance
- **preStop** - Sleep for 30 seconds. Called before receiving SIGTERM. Aim here is to sleep enough time for the current requests to finish.
- **terminationGracePeriodSeconds** - Amount of time kubernetes waits before sending us the SIGKILL signal.
Important note from the [kubernetes documentation ](https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-terminating-with-grace)on how the preStop and terminationGracePeriodSeconds interact:
> It’s important to note that this(_terminationGracePeriodSeconds_) happens in parallel to the preStop hook and the SIGTERM signal. …
> LGA-1460 - uwsgi graceful termination workaround

- cla_backend/apps/core/management/commands/worker_probes.py
- helm_deploy/cla-backend/templates/deployment-worker.yaml
Add readiness/liveness probes to worker pods
Usually the status of celery can be checked by running `celery -A cla_backend status` however there is a general issue with running any of the celery inspect commands, which is celery attempts to create `<uuid>.celery.pidbox` queues that it uses for broadcasting messages however due to the restrictive permissions on the aws sqs (cannot create new queues) this fails.
I couldn't disable these broadcasts or set the name of the queue that it broadcasts to.
> LGA-1449 - Add readiness/liveness probes to worker pods

- cla_backend/celery.py
- cla_backend/settings/base.py
- cla_backend/wsgi.py
- helm_deploy/cla-backend/values.yaml
- requirements/base.txt
Switches from Raven library to Sentry SDK. Uses a kubernetes secret that is already present, making switchover from the old Sentry instance to the new one easy.
> LGA-1450 - Sentry SDK

- bin/uat_deploy.sh
This value is used for the CLA_ENV env var, and therefore for Sentry
reporting.
On UAT, we want to know not just that it's UAT, but which specific
release (and therefore which code branch) it is. This information is
already available as $RELEASE_NAME
> LGA-1474 - UAT env names

- helm_deploy/cla-backend/templates/cron.yaml
Adds a cronjob to the cronjobs kubernetes definition, to run the send_to_performance_platform management command, weekly on Mondays at 01:01, as we did previously via the salt stack on cla_backend-deploy.
The environment variables needed by the command are already in place.
Also rename the containers of all the cronjob pods to be consistent,
rather than each having the name of the job
> LGA-1476 - Add cronjob for send_to_performance_platform

- .circleci/config.yml
- .circleci/define_build_environment_variables
Adds a "static UAT deploy" step to the Circle pipeline, with its own approval step.
Modifies the `define_build_environment_variables` script to take a second argument and use it as `DYNAMIC_HOSTNAME` to decouple the multideploy UAT behaviour from the UAT namespace (as the new release needs to be in the latter but not use the former), and modifies the pipeline to have this as a build job parameter and pass it through.
> LGA-1481 - Persistent UAT env

- helm_deploy/cla-backend/values-training.yaml
- helm_deploy/cla-backend/values-uat.yaml
Adds the staging cla_frontend template deploy IP to additional IPs for the UAT ingress (to be used by the static UAT release, rather than the dynamic multi-deploy ones)
Adds the training cla_frontend template deploy IP to additional IPs for the training ingress
> LGA-1439 - Additional whitelisting for UAT and training envs

- .circleci/config.yml
- bin/uat_deploy.sh
- helm_deploy/cla-backend/templates/deployment.yaml
- helm_deploy/cla-backend/values-uat-static.yaml
- helm_deploy/cla-backend/values-uat.yaml
- Move local postgress credentials from secret to values file. The database secret will be populated with the persistent cloud platform hosted postgres credentials
> Static UAT use cloud platform database

- cla_backend/apps/core/views.py
- cla_backend/urls.py
Logs to sentry. It only creates one event, regardless of path, but the path is broken up and available as event tags so we should be able to manage the different 404s on the Sentry platform by custom grouping and ignoring rules.
> LGA-1466 - Sentry log 404s

- cla_backend/apps/call_centre/forms.py
- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/legalaid/forms.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MICB1sSLA.sql
- cla_backend/apps/reports/tests/test_mi_sla_report.py
Use stored sla_120 and sla_480 times to determine if SMS/VOICEMAIL slas were met
Rules used to determine if SLA1/SLA2 was missed
Note: A callback attempt is when the operator has clicked the start call button after successfully contacting the user
|           |              | Callback attempted within 2 hours | Callback attempted after 2 hours AND current time within 8h window | Callback attempted after 2 hours AND current time after 8h window |
|-----------|--------------|-----------------------------------|--------------------------------------------------------------------|-------------------------------------------------------------------|
| SMS       | SLA 1 missed | FALSE                             | TRUE                                                               | TRUE …
> LGA-1440 - SMS/VOICEMAIL use stored times

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/constants.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
- cla_backend/settings/base.py
- helm_deploy/cla-backend/values-uat-static.yaml
- Remove mortgage cap
- Introduced MORTGAGE_CAP_REMOVAL_DATE setting with the date the mortgage cap is to be removed.
- **MORTGAGE CAP WILL AUTOMATICALLY BE REMOVED AFTER THE DATE IN settings.MORTGAGE_CAP_REMOVAL_DATE**
- Updated affected unittests with dictionary of pre/post mortgage cap removal expected values.
- Remove mortgage cap for all properties(main and additional properties)
- Mortgage cap removal is enabled on static-uat environment
> LGA-1542 - Remove mortgage cap

- cla_backend/apps/legalaid/tests/test_utils.py
- requirements/base.txt
Amend the unit tests to reflect the year 2020 for the holiday hours, updates the cla_common version.
> LGA-1567-christmas-hours

- docker/cla_backend.ini
http-keepalive should hopefully prevent some dropped connections that might be causing platform instability on cla-frontend and possibly cla-public, that consume the API
> LGA-1572 - Add http-keepalive config

- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/call_centre/tests/test_utils.py
- cla_backend/apps/checker/tests/api/test_case_api.py
- cla_backend/apps/cla_eventlog/management/commands/add_72h_to_context.py
- cla_backend/apps/cla_eventlog/models.py
- cla_backend/apps/cla_eventlog/tests/test_commands.py
- cla_backend/apps/legalaid/forms.py
- cla_backend/apps/legalaid/utils/sla.py
- cla_backend/apps/reports/sql/MICB1sSLA.sql
- cla_backend/apps/reports/tests/test_mi_sla_report.py
- cla_backend/settings/testing.py
- Introduces 72 hour sla(sla_72h) in the callback event context.
- Added django command that updates previous callback events to include the sla_72h in the Log.context json field
- **This will update all existing cases, please review carefully as it should not create any case logs or external communications**
- Updated legalaid.utils.sla.get_sla_time so that it calculates working hours in some edge cases
- When the start_time is within current working hours (i.e. 5PM) but the `minutes_delta` would  take you into the next working day, it would include the hours in between in the return sla
- **Please carefully review this change as this method underpins the entire reporting**
- Updates previous tests that asserted the values of Log.context.
- Rewrote/restructured tests …
> LGA-1441 web and phone 72 hours SLA

- cla_backend/apps/complaints/views.py
This amends the SQL query that runs when in the frontend dashboard they are viewing all complaints that are not closed or voided.
> LGA-815: Slow complaints tab

- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/test_tasks.py
- cla_backend/apps/complaints/views.py
- requirements/testing.txt
The was an issue with old complaints appearing in the complaints list.  What was found was a task called DeleteOldData which was a task that would regularly delete data over two years old, with a recent introduction of audit logs this was no longer working and half deleting data which meant that complaints were now being displayed.
This pull request deletes the audit logs for cases and complaints so that it can successfully delete all required data.
What this should also do on the first run is delete all data that hasn't been deleted correctly.
I have put a distinct filter on the complaints list when no closed complaints are closed.
> LGA-1121-Old complaints appearing

- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/cla_provider/tests/test_helpers.py
- cla_backend/apps/legalaid/models.py
- cla_backend/settings/base.py
This allows for automatic provider allocation to happen with discrimination providers.
> LGA 1568 discrimination provider allocation

- cla_backend/apps/knowledgebase/admin.py
- cla_backend/apps/knowledgebase/management/commands/grant_cla_superusers_article_categories_permissions.py
- cla_backend/apps/knowledgebase/tests/admin/test_command.py
Allow CLA super users to create Article Category models.
It seems we were adding article categories using a management command https://github.com/ministryofjustice/cla_backend/pull/629.
I cannot see any reason why these models cannot be created using the admin interface by at least users with the role `cla super users`.
> LGA-1550 - Allow CLA super users to create Article Category models

- cla_backend/settings/base.py
- requirements/base.txt
Will use a new version of `cla_common` to allow for finer control of weekday opening hours
Uses this to set the new education opening hours to Monday-Wednesday
Will need switching to a tagged version of `cla_common` once that is available: using a branch name for now
While a lot of this code can merge in early, the setting of `NON_ROTA_OPENING_HOURS["education"]` itself is a go-live operation
> LGA-1691 - Business hours change

- cla_backend/apps/call_centre/forms.py
- cla_backend/apps/call_centre/tests/test_forms.py
- cla_backend/apps/cla_provider/forms.py
- cla_backend/apps/cla_provider/tests/test_forms.py
Matter type selection was being enforced,  which in turn meant that cases with categories that dont have matter types can be assigned or split.  The validation for enforcing matter types has been removed and the code checked to make sure that it doesnt require them anywhere else.
> LGA 1604 Split cases

- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_eventlog/management/commands/find_and_delete_old_cases.py
- cla_backend/apps/cla_eventlog/tests/test_find_and_delete_old_cases.py
- Creates a `FindAndDeleteCasesUsingCreationTime` class
- This is used by a `Command` class. The command does 3 things based on the arguments passed in:
1.  Finds old cases - an old case being a case that is 2 years ago or older and it's most recent log is 2 years old or older
- If this command is run from a **test suite**, it will return all cases found
- If this command is run from **cmd line**, it will print out the number of cases found 
2. Deletes cases - deletes all old cases that meet the criteria above
- Subclass the `DeleteOldData` class, so we can make use of the delete functionality 
- Override the `get_eligible_cases` method, so we can change what time `now` refers to (using the `freezetime` library)
- Create test cases based on [these test …
> [WIP] LGA-1121 - Old complaints appearing in complaints tab on CHS

- cla_backend/apps/legalaid/management/commands/recalculate_assigned_out_of_hours.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/tests/test_timezones.py
- requirements/base.txt
Uses the new `tz_aware` argument to `OpeningHours.available()` to calculate the value of `assigned_out_of_hours` in a timezone-aware, and therefore correct, way.
eg during Daylight Saving Time, 08:30 UTC represents 09:30 BST and therefore the comparison of this datetime to opening hours of 9-5 should be done treating the latter as 08:00 UTC - 16:00 UTC to get accurate results.
The `__contains__` method on `OpeningHours`, that is used by Python for `if dt in object`, continues to use the old behaviour (calling `.available()` with no arguments) for backwards compatibility, so we have switched from that syntax to explicitly calling the `.available()` method with the argument.
This PR also adds a management command to correct records (by simply recalculating the value now) back as far as a …
> LGA-1719 - Timezone-aware assigned_out_of_hours calculation

- cla_backend/apps/cla_eventlog/management/commands/find_and_delete_old_cases.py
- cla_backend/apps/cla_eventlog/tests/test_find_and_delete_old_cases.py
- Creates test cases for deleting logs created by users with a **digital.justice.gov.uk** email
- Logs created by users with a non digital.justice.gov.uk email **will not be deleted**
- Let us potentially filter more old cases/complaints to be queued for deletion
- Delete logs by passing a `delete-logs` parameter to the command
- Create conditionals depending on whether the command is called in the terminal/test suite
- Refactor command handling due to linting errors complaining code was too complex
Coveralls failing due to some of the code only accessible/used in the terminal and not in the test suite
> LGA-1721 Delete old cases and complaints

- cla_backend/apps/reports/api.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/management/commands/mi_cb1_report.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
- cla_backend/assets/admin/js/ReportTask.js
- cla_backend/settings/base.py
- cla_backend/templates/admin/reports/base.html
- helm_deploy/cla-backend/templates/cron.yaml
- helm_deploy/cla-backend/values-uat.yaml
- helm_deploy/cla-backend/values.yaml
This pull request is a small redesign of the CB1 MI report.
- A new command has been created which runs the report for the current sunday to sunday.  This is scheduled via the cronjobs to run on 5am sundays.
- View code around the display of reports has been refactored to be clearer in its objective.
- As well as get reports for specific user there is now a route which will give you all the scheduled reports that have been produced.
- JS has been amended, if the report is scheduled we no longer display a delete link for it.
- The new route for showing the *scheduled* cb1 MI reports is behind the feature flag SHOW_NEW_CB1 which can be set to true or false.  Note:  I have increased the day limit on the report to 8 days and this is not behind the feature flag.
> LGA 1707 cb1 report scheduling

- cla_backend/settings/base.py
Read SECRET_KEY from environment variable
Ideally I wanted this to be `os.environ["SECRET_KEY"]` but circleci is not detecting the environment variable that determines which setting file to use. This can be done separately as it probably requires more time to investigate why this is happening and this work is required to go out as soon as possible.
Possible impact after merging this PR:
Users being logged out
> Read SECRET_KEY from environment variable

- README.md
- app.json
- bin/create_db.sh
- Adds guidance notes fixture `initial_guidance_notes.json` as part of data to be loaded into DB
- Updated README to reflect this change (will require us to run `./manage loaddata initial_guidance_notes.json` command to apply the change)
> LGA-1500 Add guidance notes fixture as part of data to be loaded into DB

- cla_backend/apps/cla_auth/views.py
- helm_deploy/cla-backend/values-uat.yaml
Add additional logging for 400 bad request responses.
I have exposed the following data when a user attempts to login(both failure and successful login):
- IP: This is the IP address of the request originator(not to be confused with the user attempting to login IP address.). This will either be one of the cloud platforms nat gateway IP addresses   or the template-deploy EC2 instance IP address
- USERNAME
- CLIENT_ID
- GRANT_TYPE
- HTTP_REFERER
- HTTP_USER_AGENT
- FORM_ERRORS
> LGA-1746 - Add additional logging for 400 bad request responses

- .coveragerc
I have amended what gets omitted from the coverage report.
It no longer counts tests, migrations, settings and other files that are used but not generally covered by unit tests.
This will unfortunately lower our coverage by roughly 8% however this will more accurately reflect our test coverage.
> LGA 1459 - Coverage accuracy improvements

- cla_backend/settings/base.py
This reduces the Sentry traces sample rate by a half to avoid transactions across MoJ being rate limited. This month [we've hit our rate limit](https://sentry.io/organizations/ministryofjustice/stats/?dataCategory=transactions&pageStatsPeriod=14d&transform=periodic) only half way through the month so I'm looking to reduce the sample rate across our apps which send the most to Sentry. https://github.com/ministryofjustice/hmpps-book-secure-move-api/pull/1529 is an example for `hmpps-book-secure-move-api`.
I hope reducing the sample rate by a half doesn't affect your application too much.
> Reduce Sentry traces sample rate

- .circleci/config.yml
Amended kube auth and what contexts are used as part of removing deprecated kube-auth-setup.
> LGA 1911 remove setup-kube-auth

- .circleci/authenticate_with_kubernetes_cluster
- .circleci/config.yml
Remove missed setup-kube-auth in cleanup_merged job
Create reusable script to authenticate with cluster.
Remove missed setup-kube-auth in cleanup_merged job
> LGA-1936 - Create reusable script to authenticate with cluster

- cla_backend/apps/reports/sql/obiee/export_legal_aid_eligibility_check.sql
Add disregards in the eligibility report
If Yes is given as answer to any disregards then use a value of "Yes" or  a value of "No" in the eligibility report
Due to the disregards column being an json object and not an array, I couldn't find a way to check if the object contained any True value within the same main query.
If the column was a json array or a postgres then I could have used a function like the ANY function to check if it contained a True value.
The other option was to introduce a new has_any_disregards column to contain True if any disregards were selected but I think the chosen approach does this without the additional column.
> LGA-1806 - Add disregards in the eligibility report

- requirements/base.txt
Update to version 0.2.2, which is the same as 0.2.1 but with submodules
defined using the https:// protocol instead of the git:// protocol, to
allow them to continue to be installed
> LGA-1971 - Update forked django-pagedown

- .circleci/config.yml
CLA Backend UAT Live-1 Clean-up
The cleanup_merged_live1, uat_deploy_live_1 and static_uat_deploy_live_1 deployments have been removed from the circleci config
Required.
> LGA-1948 CLA Backend UAT Live-1 Clean-up

- helm_deploy/cla-backend/templates/deployment-worker.yaml
Increase timeoutSeconds for worker pods probes
It seems that on the new cluster the worker pod probes were taking longer than 2 seconds and was causing the pod to crash loop.
> Increase timeoutSeconds for worker pods probes

- helm_deploy/cla-backend/templates/ingress.yaml
Remove deprecated extensions/v1beta1 ingress api version and use networking.k8s.io/v1
> LGA-1933 - Remove deprecated extensions/v1beta1 ingress api version and use networking.k8s.io/v1

- cla_backend/apps/status/middleware.py
- cla_backend/apps/status/views.py
- cla_backend/settings/base.py
- cla_backend/templates/maintenance.html
- cla_backend/urls.py
- helm_deploy/cla-backend/templates/ingress.yaml
- helm_deploy/cla-backend/values.yaml
Add maintenance mode page
Add `MAINTENANCE_MODE` environment variable that is set from a K8 `maintenance-mode` configmap
Add annotation to exclude 503 error pages from the list the cloud-platform error pages and use our error pages for 503 errors
> LGA-2081 - Add maintenance mode page

- .circleci/config.yml
Pull down the latest version of the end-to-end-tests orb
Requires https://github.com/ministryofjustice/cla-end-to-end-tests/pull/63
> LGA-1967 - Pull down the latest version of the end-to-end-tests orb

- helm_deploy/cla-backend/templates/ingress_v122.yaml
Creates new ingress file to do upgrade prior to move to Kubernete 1.22.  Helm will assume you want to delete the existing ingress if you only change the current file to create a new ingress.
Helm adds  it’s own annotations: `app.kubernetes.io/managed-by: Helm` and `helm.sh/chart: cla-backend-0.1.3`; because of this if you make changes directly to  <old-ingress-name> and recommit, helm considers the ingress to be a new version of the same resource and deletes the old one. This leads to downtime.
This is a multistep process - first weighting is set to zero for existing 1.21 ingresses, then once this new file has been added and it is verified that traffic is passing through the new v1.22 ingress, the old ingress can be deleted in kubectl and then a further two separate commits will be …
> LGA-2123 v1.22 Update ingress for Kubernetes 

- requirements/base.txt
Use forked version of django-moj-irat that supports django1.7
The current main repo for django-moj-irat requires django>=1.8,<1.9
We are looking to switch to pip-tools and the version that is compatible with our python version does not yet support resolving version mismatch
> LGA-2216 - Use forked version of django-moj-irat that supports django1.7

- cla_backend/settings/base.py
Updated all of the rota opening hours to use environment variables. This means they can be set without changing the code.
There are defaults set in case these are not set.
This change is primarily so we can run out of hours end to end tests.
Have also removed the code creating a  JULY_EDUCATION_FEATURE_FLAG, this will need to be removed from the configMap as well.
> Feature/lga 2236 Update Opening hours to use env variables

- helm_deploy/cla-backend/values-staging.yaml
When comparing pre and post migration reports, it seems as though not all the files were not the same. This PR makes the application point back at database-10 so can see if there was an issue with the migration.
Trying to rule out the issue being with this or the oauth change.
> LGA-2164 Roll back database-11 changes

- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
Upgrade requirements to use django 1.7.11 - this is a minor upgrade and should not need any other changes.
> LGA-1771 - update django to version 1.7.11

- bin/database-migration/Dockerfile
- bin/database-migration/migration_validation.py
- `pgDataDiff` requests `md5` hashes for "chunks" of data and using this to do a fast comparison. At the moment the `chunk_size` has been set to 100k. This means that the comparison is fast but we won't be able to pinpoint the exact row where the difference exists.
> LGA-2291: Update migration validation script

- cla_backend/apps/call_centre/tests/api/test_case_api.py
There were no tests for the assign suggest view. This view failed when django rest framework was updated, decision made to add in extra coverage.
This is the view associated with clicking "assign" when creating and assigning a case on the HGS. You can click the tab and it hits the api even if there are validation errors from the frontend. Hence needing to check no category options.
It returns a response with the format:
`{"suggested_provider": *, "as_of": "date_time",
"suitable_providers":
[{"name": "*", "id": pk, "short_code": "*",
"telephone_frontdoor": "*", "telephone_backdoor": "0845 122 8677"}, ...]}`
If the case has a category assigned then suitable_providers will be for only that category. 
If there is no category assigned to a case then suggested_provider will be None and …
> LGA-2287 - Create Unit Tests for Assign Suggest View

- cla_backend/apps/call_centre/views.py
- cla_backend/apps/checker/views.py
- cla_backend/apps/cla_provider/views.py
- cla_backend/apps/complaints/views.py
- cla_backend/apps/core/drf/decorators.py
- cla_backend/apps/core/drf/router.py
- cla_backend/apps/core/routers.py
- cla_backend/apps/core/serializers.py
- cla_backend/apps/diagnosis/views.py
- cla_backend/apps/legalaid/fields.py
- cla_backend/apps/legalaid/views.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- Update Django Rest Framework(DRF) to 2.4.8
- Update DRF Nested Routes package to 0.9.0
- Remove usage of deprecated `@action` and `@link` decorators in favour of recommended `@detail_route`
[2.4 Announcement ](http://www.tomchristie.com/rest-framework-2-docs/topics/2.4-announcement)
[2.4 release notes](https://github.com/encode/django-rest-framework/blob/version-2.4.x/docs/topics/release-notes.md#240)
The update to DRF Nested Routes was required because the previous version [0.1.3 stopped working with DRF 2.4](https://github.com/alanjds/drf-nested-routers/issues/24)
rest_framework.compat no longer exists in DRF 2.4  - [rest_framework.compat.url was imported from django.conf.urls.url](https://github.com/encode/django-rest-framework/blob/2.3.14/rest_framework/compat.py#L22), so we …
> LGA-1772 - Update Django Rest Framework(DRF) to 2.4.8

- helm_deploy/cla-backend/values-uat-static.yaml
> LGA-2156: Clean up postgres 10 usage in UAT

- helm_deploy/cla-backend/values-training.yaml
> LGA-2158: Training references to database-11 secret removed.

- cla_backend/apps/cla_auth/tests/test_views.py
- cla_backend/settings/base.py
There was concern from users about how this would effect report generation which is sometimes longer than 30mins. I have checked the code and it looks like the report generation is run asynchronously by Celery so the session timeout will not effect the generation itself however the users will stilled be logged out if idle for 30mins. The reports will appear in the list to download when users log back in.
> LGA-2122: Set session timeout for fox admin.

- cla_backend/apps/legalaid/migrations/0031_personal_details_contact_for_research_method.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/serializers.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
Updated DRF to 3.2.5
Remove group from ContactResearchMethodSerializerBase as it doesn't seem to do anything and was failing tests -looks like this field was added by mistake and is not in Meta.fields
Updated contact_for_research_methods property as required by upgrade and created associated migration.
Errors I had in 3.2.5. 
Change in behaviour:
https://www.django-rest-framework.org/community/3.2-announcement/#manytomany-fields-and-blanktrue
https://github.com/encode/django-rest-framework/issues/2804
Impact is this field here:
https://github.com/ministryofjustice/cla_backend/blob/06311d6831c8866d0780827d2f22e780533da2af/cla_backend/apps/legalaid/models.py#L145
There is no blank=True so it now thinks that there should be a value and won't allow an empty list which is what we had before. …
> LGA-1775 update django rest framework 3.2.5

- .circleci/config.yml
- helm_deploy/cla-backend/templates/ingress_v122.yaml
Removing snippet and putting ModSecurity into dection mode only.
Required.
[Kibana](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/goto/ae8948f736fbcbf6346bd118dccbf8a3)
[LGA-2313](https://dsdmoj.atlassian.net/browse/LGA-2313)
[LGA-2313]: https://dsdmoj.atlassian.net/browse/LGA-2313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LGA-2313 Enabling Modsecurity in detection mode for cla_backend

- .circleci/config.yml
Update build job docker image to use latest cloud-platform image
The previous cloud-platform/tools:circleci image is out of date and is using out of date ubuntu version that is missing latest lets encrypt root certificate which was causing our slack notifications not to go out. 
https://app.circleci.com/pipelines/github/ministryofjustice/cla_backend/2668/workflows/435b3775-cc54-49b7-81ad-540e34d7d650/jobs/13559?invite=true#step-106-64
> LGA-2412 - Update build job docker image to use latest cloud-platform image

- cla_backend/apps/cla_provider/migrations/0003_auto_20230405_1449.py
- cla_backend/apps/cla_provider/models.py
- cla_backend/apps/cla_provider/tests/test_models.py
The MI Allocation Provider report fails when there is a duplicate case sensitive provider name. (IE - "Test" and "Test" fails, whereas "Test" and "test" would not fail)
To ensure that provider name is unique (in a case sensitive manner as above), this PR:
- updates the provider model 
- adds a migration file
- adds a unit test 
Updating the model pushes an error to the django form as seen in the screenshot below:
> LGA-2416 Make provider name unique to prevent CLA provider report fail

- cla_backend/apps/diagnosis/data/graph.graphml
- cla_backend/apps/diagnosis/data/graph.graphml.tpl
- cla_backend/translations/cy/LC_MESSAGES/django.po
- cla_backend/translations/en_GB/LC_MESSAGES/django.po
- Updates the GraphML to include a Special Guardianship Order
- If Special Guardianship order is selected, offers 2 new (radio button) options:
> - Parental figure chosen. If this is chosen, skips means assessment
> - Other person chosen. If this is chosen, continue to create means assessment
Created end-to-end tests that passed when run locally [link to branch](https://github.com/ministryofjustice/cla-end-to-end-tests/pull/101)
> LGA-2459 Update graphml to reflect change in family scope

- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/complaints/models.py
- cla_backend/apps/diagnosis/graph.py
- cla_backend/apps/legalaid/management/commands/recalculate_assigned_out_of_hours.py
- cla_backend/apps/legalaid/tests/test_timezones.py
- cla_backend/apps/legalaid/tests/views/mixins/case_api.py
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/views.py
- cla_backend/settings/base.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
- requirements/source/requirements-testing.in
Upgrade Django to 1.8.19
https://docs.djangoproject.com/en/1.8/releases/1.8/
Major changes seen in this version of Django:
- Changes to the way templates are managed, have updated the settings as described in the announcement.
- Changes to the permissions for the usertools block - see miscellaneous changes in the release notes: https://docs.djangoproject.com/en/4.1/releases/1.8/#miscellaneous
- Changes to management commands, now use argparse instead of optparse as standard so needed to change the way parameters are passed in for custom commands.
- Changes to TestCase data setup. Removed setUpClass from test_case_api and replaced with setUpTestData that calls cls, resolving the cls atomics issue.  All test setup is now included in `setUpTestData` instead of `setUpClass`. Link to …
> LGA-1777 django upgrade 1 8 19

- .circleci/config.yml
- bin/create_db.sh
- cla_backend/apps/legalaid/fixtures/new_media_codes.json
Added new fixture date for media code
This will then be added on the required data by running a command on required date (this could also be scheduled if need be).
To run the load of the fixture, this command would need to be ran on a pod in production: 
kubectl exec -ti <pod_name>  python manage.py loaddata new_media_codes.json
> LGA 2506 Shelter Media Code

- .circleci/config.yml
- cla_backend/apps/reports/sql/MISurveyExtract.sql
As per the investigation completed in the spike LGA-2408, this PR uses the postgres v14 image by:
- updating the circleci postgres image from 11.6 alpine to 14.7 bullseye
- Updating the MISurveyExtract.sql file to pass our unit tests when upgrading to allow upgrade past v11.14 (see highlights for more info)
1. When upgrading from v11.13 to v11.14 2 unit tests trigger and fail:
```
ProgrammingError: in an aggregate with DISTINCT, ORDER BY expressions must appear in argument list
LINE 18: ..._agg(DISTINCT cc_org.name::varchar, ', ' ORDER BY cc_org.nam...
```
Based on the v11.14 documentation this is due to postgres no longer ignoring unspecified cast type modifier:
> Don't discard a cast to the same type with unspecified type modifier (Tom Lane)
> 
> For example, if column f1 is of type …
> LGA-2467 make cla_backend pipelines use postgres v14 image

- bin/maintenance_mode.sh
Puts cla_frontend and cla_public in and out of maintenance mode when putting cla_backend into maintenance mode
> Flick dependant apps in out of maintenance mode

- cla_backend/apps/core/drf/fields.py
- cla_backend/apps/legalaid/tests/views/mixins/personal_details_api.py
Force ValidationError message to a string
The previous field implementations did not forcibly coerce returned values into the correct type in many cases. For example, an ValueError would return a string output if used in a string context. We now more strictly coerce to the correct return type, leading to more constrained and expected behavior
https://www.django-rest-framework.org/community/3.0-announcement/#coercing-output-types
> LGA-2569 - Force ValidationError message to a string

- cla_backend/apps/checker/tests/api/test_eligibility_check_api.py
- cla_backend/apps/cla_provider/serializers.py
- cla_backend/apps/cla_provider/tests/api/test_eligibility_check_api.py
- cla_backend/apps/legalaid/tests/views/mixins/eligibility_check_api.py
Update provider PersonSerializer so the frontend can send partner savings as null
> LGA-2601 - Update provider PersonSerializer so the frontend can send partner savings as null

- .circleci/config.yml
Approval to deploy changes to production only after deploy to training is green
Implemented this in a way so that the pipelines first pass staging, then pass training then pass production
> LGA-2625 deploy to production requires staging and training

- bin/database-migration/migration_reports.sh
Add script used for testing reports are similar before and after migration. 
To use this script:
- you must have your files in a pre-migration directory and a post-migration directory.
- Each of these directories must have an empty directory called SORTED
- make the script executable by using `chmod +x <fileName>`
- run using `./bin/database-migration/migration_reports.sh <PRE_FOLDER> <POST_FOLDER>`
> LGA-2514 add script to test reports are consistent after migration

- Dockerfile
Remove a / from the dockerfile that was preventing CLA_Backend from building locally.
> LGA-2624 Removed / from firefox-esr

- cla_backend/apps/notifications/models.py
Temporarily disable pushing notifications to the socket server
At the moment after receiving the notification, the socket server does not send the notification to the user due to it being setup incorrectly See https://github.com/ministryofjustice/cla_frontend/pull/919 for more details
Also the scheduling of these notifications with long ETA's is causing duplicating messages(thousands) to fill up the message queue, this means reports or anything else that depends on the message queue will not work until the queue is purged manually
> LGA-2673 - Temporarily disable pushing notifications to the socket server

- Dockerfile
Upgrade base alpine image to 3.15
The py2-pip package that was used to install is not available in alpine3:15. Instead we used pythons builtin ensurepip module to install pip
> LGA-2426 - Upgrade base alpine image to 3.15

- helm_deploy/cla-backend/templates/cron.yaml
Remove deprecated batch/v1beta1 API version of CronJob
[The batch/v1beta1 API version of CronJob is no longer served as of v1.25.](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125)
> LGA-2727 - Remove deprecated batch/v1beta1 API version of CronJob

- cla_backend/settings/base.py
Changes `EMAIL_ORCHESTRATOR_FLAG` to `USE_EMAIL_ORCHESTRATOR_FLAG`, as is named elsewhere.
> bug/LGA 2770: Renamed EMAIL_ORCHESTRATOR_FLAG to USE_EMAIL_ORCHESTRATOR_FLAG

- helm_deploy/cla-backend/templates/cron.yaml
- Gives all CronJobs a serviceAccountName so they are being executed with permissions to interact with AWS resources such as S3/ RDS
> LGA 2821: Fix CronJobs failing due to not having AWS Credentials

- cla_backend/apps/cla_butler/tasks.py
- cla_backend/apps/cla_butler/tests/mommy_recipes.py
- cla_backend/apps/cla_butler/tests/test_tasks.py
- Fixes a bug where the the CronJob delete-unused-cases was repeatably failing every day at 5:00 due to
```
django.db.utils.IntegrityError: update or delete on table "legalaid_personaldetails" violates foreign key constraint "x" on table "cla_butler_diversitydatacheck
```
- This fixes the issue by deleting linked `diversity data check` data before removing `personal details`.
- Adds unit testing for cases where diversity data should be deleted or not.
> LGA 2852 Fix delete unused cases cronjob failing

- cla_backend/apps/checker/models.py
- cla_backend/apps/reports/tests/test_reports.py
Correct `with cases` and `without cases` data when exporting reason for contacting for a particular referrer
> LGA-2773 - Data extract - Reason for contacting (aggregated - referrers)

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_income.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Translate income without earnings(earnings, self_employment_drawings) into cfe-civil `regular_transactions`
JIRA: https://dsdmoj.atlassian.net/browse/LEP-435
```json
{
"you": {
"income": {
#"earnings": 100000,
"tax_credits": 0,
"maintenance_received": 0,
"pension": 0,
#"self_employment_drawings": 0,
"benefits": 0,
#"self_employed": false,
"child_benefits": 0,
"other_income": 0
}
}
}
```
> LEP-435 income translator

- cla_backend/settings/circle.py
e.g. if you do:
python manage.py test --settings=cla_backend.settings.circle cla_backend.libs.eligibility_calculator.tests.test_calculator.DoCfeCivilCheckTestCase
> Suppress INFO logging during tests

- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/serializers.py
- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/models.py
Adds logging of:
* CaseData
* Exceptions raised by legacy_check()
Logging of the big dictionaries is rather verbose for normal use, so these are demoted to DEBUG level. These can be displayed if you change the log_level, but for local development it's easiest to just temporarily change the log statements to `logger.info(`...
> Logging improved - including CaseData

- cla_backend/libs/eligibility_calculator/calculator.py
Previously the date was hard-coded.
The correct date for the calculation would be the day of application, but CLA might be days or weeks in the future. Today seems a reasonable date to choose.
At some point we'll have tests of this function, so I've provided an optional param to fix the date to a known one.
> Submission date is today

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/applicant.py
- cla_backend/libs/eligibility_calculator/cfe_civil/proceeding_types.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_applicant.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_proceeding_types.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
- Translate **CLA** `category(immigration)` to **CFE** `proceeding types[{"ccms_code": "IM030"}]`
- Translate **CLA** `on_nass_benefits` to  **CFE** `receives_asylum_support`
- Skip **CLA** Legacy check for `on_nass_benefits`
JIRA: https://dsdmoj.atlassian.net/browse/LEP-442
> LEP-442 translator for on nass benefits

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/conversions.py
- cla_backend/libs/eligibility_calculator/cfe_civil/dependants.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/cfe_civil/property.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_income.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_property.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Provide 'incomplete' sections to cfe-civil, so that it can reply 'not_yet_known' if the request is incomplete and the calculation cannot be performed from the given data
Add a local check for 'has_partner' being available (unknown if not available), as CFE cannot be told an 'unknown' value for partner - it defaults to false
> Lep 456 unknown capital check

- cla_backend/apps/complaints/tests/test_complaints_api.py
Fix flaky test_search_find_multiple_results_by_person_name unit test by removing default resource
It has been reported that the `complaints.tests.test_complaints_api.SearchComplaintTestCase.test_search_find_multiple_results_by_person_name` unit tests sometimes fails due to 3 results being returned when only 2 results are expected.
In the setUp of `SearchComplaintTestCase`  , 3 complaints are created, but only 2 of those cases have a personal_details field which contain the searched text `abc
However the `SearchComplaintTestCase` classes uses the mixin `SimpleResourceAPIMixin`
And `SimpleResourceAPIMixin` creates a Complaint object(which needs a case and a case creates a personal_details object which it needs)
The fields for the resource created by `SimpleResourceAPIMixin` have all random …
> LGA-2905 - Fix flaky test_search_find_multiple_results_by_person_name unit test

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
Analysis revealed that calcs.liquid_capital actually means "total capital not including properties".
(We are planning on renaming the field to reflect that: https://github.com/ministryofjustice/cla_backend/pull/1064 )
This ticket restores the tests that were "fixed" https://github.com/ministryofjustice/cla_backend/pull/1055/files#r1430269652
and ensures that CFE's non_liquid_capital amount is also included in calcs.liquid_capital so that the tests pass.
> Fix liquid capital calculation

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
The creation of the calcs seems less like a concern at the is_eligible() level, and more suited to this translator of the CFE response.
> Move CFE calcs creation down into _translate_response

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/dependants.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/cfe_civil/property.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
The older version of this logic (_complete_cfe_capital_data() and _complete_cfe_income_data()) is removed, that is an accidental left-over from when it was replaced in [lep-456-complete-logic-is-centralized](https://github.com/ministryofjustice/cla_backend/pull/1067/files).
> LEP-456 Remove older version of section_incomplete logic

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
merge rather than overwrite savings and disputed savings
> stop disputed and non-disputed savings overwriting each other

- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
Before this PR, the calcs only looked at the value of the first property. When you input multiple properties, the calcs diverge from what legacy calcualtor's calcs give:
This PR adds together all the property equities to get the property_capital. With this change the results match the calcs from the legacy calculator
> Fix calcs for multiple properties

- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
- cla_backend/libs/eligibility_calculator/tests/test_util.py
Suppress error logging in tests where its not important
The errors look like:
Running tests...
----------------------------------------------------------------------
ERROR CFE and legacy_check() results disgree! yes no
..ERROR CFE and legacy_check() results disgree! yes no
.ERROR CFE and legacy_check() results disgree! yes no
..ERROR CFE and legacy_check() results disgree! yes no
.ERROR CFE and legacy_check() results disgree! yes no
.
----------------------------------------------------------------------
Ran 7 tests in 1.384s
These have been investigated and are due to bits of the calculator being mocked during tests, and off-by-one errors in the calculations. So suppressing the distracting display.
> Suppress error logging in tests where its not important

- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_deductions.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
- cla_backend/libs/eligibility_calculator/tests/test_calculator.py
This exception is reproducible in cla_public by submitting the /about page.
Bug was introduced in removal of [if has_all_attributes](https://github.com/ministryofjustice/cla_backend/commit/2dd026b86bd9a3d8ec46cf9b167cb3595d1e0e2f#diff-300532217fc83e73a204585a037bdaa0b307a630d5c92a0336b23762d6f75f4dL15) line, and associated tests, which are here restored.
> Fix savings exception

- cla_backend/libs/eligibility_calculator/cfe_civil/age.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
- cla_backend/libs/eligibility_calculator/cfe_civil/deductions.py
- cla_backend/libs/eligibility_calculator/cfe_civil/dependants.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
- cla_backend/libs/eligibility_calculator/cfe_civil/income.py
- cla_backend/libs/eligibility_calculator/cfe_civil/proceeding_types.py
- cla_backend/libs/eligibility_calculator/cfe_civil/property.py
- cla_backend/libs/eligibility_calculator/cfe_civil/savings.py
- cla_backend/libs/eligibility_calculator/cfe_civil/under_18_passported.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_deductions.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_dependants.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_employment.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_income.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_proceeding_types.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_property.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_savings.py
Because black has been used on this repo in the past.
And we might as well be consistent.
How I did this:
Newer black versions don't install on python2, so I created a separate virtual environment to install and run it:
```
python3 -m venv /tmp/venv3
/tmp/venv3/bin/pip install black
/tmp/venv3/bin/black FILENAME
```
> Autoformatting with black, files new to cfe-integration branch

- cla_backend/libs/eligibility_calculator/cfe_civil/conversions.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
Previously we wanted all the fields present, because it was tied up with figuring out if the "section was complete". However "section complete" functionality is entirely separate. So we can simply translate any and every field in CaseData and not worry about completeness.
> Remove check for all income/deduction fields in employment translator

- bin/database-migration/Dockerfile
This change was originally done by @said-moj: https://github.com/ministryofjustice/cla_backend/commit/7684f8559553f49e640c7e336f08fee2f2a4135e
for reason:
>  Update migration script to support pg_dump version 15 
Moving that change to this separate PR, to avoid it being mixed into the large cfe-integration branch.
> Update migration container alpine image

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/applicant.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_applicant.py
Not that NASS is in either of the UIs, but it's in the API so we should support it as best we can.
NASS passporting is more powerful than normal passporting, skipping the capital test too, so if the case qualifies for both then we must tell CFE about both.
> Fix - NASS was ignored if normal passporting benefit was present

- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
* Changed `is_you_under_18` to `under_18_passported`. Because if case is under_18_passported, then I would agree that that is enough info to be calling CFE with. However if the applicant is under 18, but not under_18_passported, then we can not skip the other rules.
* Moved `has_partner` to the GI/DI/capital sections_complete. If we do not know if they have a partner, then we can still run CFE, and any non-means rules will run fine. Its just that all the GI/DI/capital figures are incomplete until we clear up if they have a partner.
> Fix is_applicant_detail_section_complete

- cla_backend/settings/base.py
Because CFE-Civil UAT is really only for the EP team to use - it allows us to break it occasionally. Since going forward this will be for the CLA team, I think I would prefer staging here, i.e. for use by the CLA team during their local development. And maybe there will be other times when CFE_URL fails to be set accidentally, and it would be better to using staging than our day-to-day UAT.
> CFE Staging used during CLA development

- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/tests/test_models.py
- cla_backend/apps/legalaid/tests/views/mixins/eligibility_check_api.py
- cla_backend/libs/eligibility_calculator/calculator.py
- cla_backend/libs/eligibility_calculator/cfe_civil/cfe_response.py
Convert is_eligible() call to is_eligible_with_reasons() so that the reasons are known by the caller without having to call the checker again or to do some awkward caching of the result
> LEP-478 Fixup is_eligible() caller to obtain reasons at the same time

- helm_deploy/cla-backend/values.yaml
Digital VPN is [disappearing soon](https://mojdt.slack.com/archives/C67Q5TN57/p1698421193318189). 
This PR gives access via Global Protect VPN instead.
IP addresses from GP are listed here:
* https://github.com/ministryofjustice/moj-ip-addresses/blob/main/moj-cidr-addresses.yml#L296
* https://mojdt.slack.com/archives/C06ATC097B5/p1702994991148149
Tested:
This PR doesn't remove access from "MoJ Digital Wifi & Digital VPN". Rather than switch off access from that in this same deployment, I suggest we have a short period of overlap, where both VPNs can be used, to allow all devs to check the new arrangement works for everyone. So removing the "MOJ Digital VPN" IP from this list can be a follow up change.
> LGA-2884 Allow access from Global Protect VPN

- cla_backend/libs/eligibility_calculator/cfe_civil/employment.py
- cla_backend/libs/eligibility_calculator/tests/cfe_civil/test_employment.py
Looks like we forgot to test for the attribute existing before access it.
What keys are present in CaseData depends on what gets stored by the API client, and there are are no controls - so we have to cope with any not being present..
test_missing_income_tax reproduces the exception seen:
PropertyExpectedException
Deductions requires attribute income_tax and was not given at __init__
cla_backend/libs/eligibility_calculator/cfe_civil/employment.py:10
test_missing_national_insurance reproduces a similar one for national insurance.
> LEP-483 Fix exception for missing income-tax

- cla_backend/settings/base.py
- requirements/generated/requirements-dev.txt
- requirements/generated/requirements-docs.txt
- requirements/generated/requirements-production.txt
- requirements/generated/requirements-testing.txt
- requirements/source/requirements-base.in
Add secure cookie settings and headers per ithc recommendation
`SESSION_COOKIE_SAMESITE` is part of django core from 2.1. Using https://github.com/jotes/django-cookies-samesite in the meantime to add the samesite attribute
> LGA-2739 - ITHC secure cookies and headers

- cla_backend/apps/cla_provider/helpers.py
- cla_backend/apps/cla_provider/tests/test_helpers.py
Modifies the `get_qualifying_providers_allocation` and `get_qualifying_providers` functions to always return all providers in a category regardless of their working days or capacity.
This ensures that all education providers are passed to the frontend so cases can be manually allocated to all SPs.
> LGA 2988: Manually assign education cases to all providers

- helm_deploy/cla-backend/values.yaml
Just a bit of cleanup leftover from:
https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/boards/226?assignee=557058%3A013dab21-b9d3-42a5-8be7-ebc76789671d&selectedIssue=LGA-2884
Remove old networks that are not used by users and are not reported on logs
Removing live0 and live1 as I can't see the benefit of keeping these. Please stop me if there's a reason. CP traffic doesn't go through ingress right?
https://lga-2884-remove-unused-ips-laa-cla-backend-uat.apps.live-1.cloud-platform.service.justice.gov.uk/admin/legalaid/mattertype/
Export report works fine but can't see them, assuming this is normal for dynamic UAT. This works fine on Static UAT though.
> LGA-2884 Remove unused IP addresses

- cla_backend/apps/checker/admin.py
- cla_backend/apps/checker/call_centre_availability.py
- cla_backend/apps/checker/tests/api/test_callback_time_slots.py
- cla_backend/apps/checker/views.py
- Making a single Case query to load relevant data at the start of the operation, rather than once per time slot.
- Minimised data load by only loading a list of time slots rather than whole case objects.
- Adds caching to the API query page.
- Only loading a weeks worth of data, until requested for more, rather than all callback time slot data.
> LGA-3046: Improve Callback capping performance

- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MIExtractByOutcomeTellUsAboutYourProblem.sql
- Matter Type 1 Code
- Matter Type 1 Description
- Matter Type 2 Code
- Matter Type 2 Description
> LGA 3109: Add matter types to the MITellUsMoreAboutYourProblem report

- cla_backend/apps/call_centre/serializers.py
- cla_backend/apps/call_centre/tests/api/test_case_api.py
- cla_backend/apps/checker/serializers.py
- cla_backend/apps/checker/tests/api/test_case_api.py
- cla_backend/apps/cla_provider/serializers.py
- cla_backend/apps/cla_provider/tests/api/test_case_api.py
- cla_backend/apps/legalaid/migrations/0035_case_gtm_anon_id.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/legalaid/serializers.py
- cla_backend/apps/legalaid/tests/test_models.py
For: cross-service GA tracking
Add gtm_anon_id to case data
Add support for gtm_anon_id for checker to post in and save into case data
Add support for call centre to GET gtm_anon_id from case data and auto generate for new case.
Add support for provider to GET gtm_anon_id as part of case data
Public: https://github.com/ministryofjustice/cla_public/pull/1263
Frontend: https://github.com/ministryofjustice/cla_frontend/pull/956
Backend: https://github.com/ministryofjustice/cla_backend/pull/1178
Documentation: https://dsdmoj.atlassian.net/wiki/spaces/laagetaccess/pages/4952031380/End+to+end+CLA+Google+Analytics+reporting
> Lga 3156 (spike: LGA-3075) gtm_anon_id  db cross service GA tracking

- cla_backend/apps/legalaid/serializers.py
Allow null gtm_anon_id for old cases on CHS because it updates case when someone updates personal details and otherwise expects a value for gtm_anon_id, which isn't on there.
> LGA-3156 Allow null for old cases being updated on CHS

- cla_backend/apps/legalaid/management/commands/generate_restricted_views.py
Updates the nodes field to remove the square brackets so that it can be identified as a json on metabase. This only happens in the generated view and will have no affect on the table.
Data will now appear as below:
The code ./manage.py generate_restricted_views will need to be run on the environments.
https://dsdmoj.atlassian.net/browse/LGA-3155
> LGA-3155 Update nodes field to extrapolate the json data

- helm_deploy/cla-backend/values.yaml
Adds in the 51.149.249 address to the whitelist for DOM1 users, using the Cisco VPN. IP Addresses taken from other MOJ projects https://github.com/ministryofjustice/licences/blob/d53b24c6580856a481f97be86aaca52647d1e12c/helm_deploy/values-preprod.yaml#L81
https://dsdmoj.atlassian.net/browse/LGA-3172
> LGA-3172 Bug Fix, Add in DOM1 VPN to Whitelist

- helm_deploy/cla-backend/values.yaml
The DOM1 Proxy Migration has caused the IP addresses of LAA users to change.
This PR adds additional IP blocks to the whitelist to allow access for these new inter-domain proxy IP address ranges.
> Add additional IP whitelist ranges for inter-domain routing

- bin/production_deploy.sh
- bin/staging_deploy.sh
- bin/training_deploy.sh
- bin/uat_deploy.sh
- helm_deploy/cla-backend/templates/_helpers.tpl
- helm_deploy/cla-backend/values.yaml
- Pulls IP addresses, including the new Prisma VPN from the new LAA Shared IP list: [https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt](https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt)
- Removes IP addresses that would be duplicated
> Add additional IPs from shared LAA whitelist

- cla_backend/apps/checker/call_centre_availability.py
Fixes a bug where we were converting from an unaware timezone at 01:00:00 on the 27th of October 2024 to a London timezone.
This time technically occurs twice due to switching off daylight savings time, so the date time module didn't know what timezone it belonged to, and raised an error.
> Fix Ambiguous timezone error

- .pre-commit-config.yaml
- cla_backend/apps/legalaid/migrations/0036_auto_20241002_1407.py
- cla_backend/apps/legalaid/models.py
- cla_backend/apps/reports/forms.py
- cla_backend/apps/reports/sql/MIScopeReport.sql
- cla_backend/apps/reports/sql/MiScopeReport.sql
- cla_backend/apps/reports/tests/test_reports.py
- cla_backend/apps/reports/urls.py
- cla_backend/apps/reports/views.py
- cla_backend/templates/admin/index.html
- cla_backend/templates/admin/reports/case_report.html
Add scope report
Pre-commit fails to install locally due to a dependency on pyyaml. I have pinned pyyaml to 5.3.1 which is the latest version that works locally on apple chips.
> LGA-3271 scope reports

- cla_backend/apps/legalaid/models.py
- Makes the source field visible in Metabase, as this does not contain PII.
> Remove source from PII model

- helm_deploy/cla-backend/templates/ingress_v122.yaml
Removes rule ID 932130 from the ModSec ingress which is triggering false positives on the CSV import.
> Remove false ModSec rule

- cla_backend/apps/checker/call_centre_availability.py
When the callback capacity was calculated we queried the database with for all cases with callbacks between now and `num_days` later. This means if the calculation was ran at 14:15 on the 1st of January 2025 with `num days = 7` we would look for all callbacks between 14:15 on the 1st of January 2025 and 14:15 on the 7th of January 2025.
However, the callback capacity API returns data on all callbacks between the 1st of January 2025 00:00:00 and the 7th of January 2025 23:59:59 regardless of when in the day the calculation was run.
This resulted in the system allowing callbacks to be booked 7 days in advance, ignoring the callback cap, assuming the callback time was later in the day than when the booking was being made.
Ensure we capture callback information for the entire relevant time …
> Fix callback capping

- cla_backend/apps/checker/call_centre_availability.py
- cla_backend/apps/checker/forms.py
- cla_backend/apps/checker/models.py
- cla_backend/apps/checker/tests/api/test_callback_time_slots.py
- cla_backend/apps/checker/tests/helpers/test_helpers.py
- cla_backend/apps/reports/tests/test_reports.py
- Alters the callback capacity algorithm to only include cases with an outcome code of CB1 when calculating used capacity.
- Only fire the callback threshold breached alert emails if the case which triggered the check could have reduced the capacity.
> Callback capacity only include CB1

- cla_backend/apps/legalaid/tests/test_timezones.py
- cla_backend/settings/base.py
- Updates non rota start and end times for all categories to 09:00 - 18:00.
> Update non-rota start and end times
